const dictionnaire = [
  { mot: "autoroute", genre: "féminin", sig: "highway; road; route" },
  { mot: "abeille", genre: "féminin", sig: "bee" },
  { mot: "abri", genre: "masculin", sig: "shelter; shed" },
  { mot: "absence", genre: "féminin", sig: "absence" },
  { mot: "absurdité", genre: "féminin", sig: "nonsense" },
  { mot: "abus", genre: "masculin", sig: "abuse" },
  { mot: "accent", genre: "masculin", sig: "accent" },
  { mot: "accès", genre: "masculin", sig: "access" },
  { mot: "accident", genre: "masculin", sig: "accident" },
  { mot: "accord", genre: "masculin", sig: "deal; agreement" },
  { mot: "achat", genre: "masculin", sig: "purchase" },
  { mot: "acide", genre: "masculin", sig: "acid" },
  { mot: "acier", genre: "masculin", sig: "steel" },
  { mot: "acte", genre: "masculin", sig: "act; deed" },
  { mot: "action", genre: "féminin", sig: "action" },
  { mot: "activité", genre: "féminin", sig: "activity" },
  { mot: "addition", genre: "féminin", sig: "addition" },
  { mot: "adieu", genre: "masculin", sig: "farewell" },
  { mot: "ADN", genre: "masculin", sig: "DNA" },
  { mot: "adresse", genre: "féminin", sig: "address" },
  { mot: "adulte", genre: "masculin", sig: "adult" },
  { mot: "aéronef", genre: "masculin", sig: "aircraft" },
  { mot: "aéroport", genre: "masculin", sig: "airport" },
  { mot: "affaire(s)", genre: "féminin", sig: "matter; affair; business" },
  { mot: "affection", genre: "féminin", sig: "affection" },
  { mot: "affichage", genre: "masculin", sig: "display" },
  { mot: "âge", genre: "masculin", sig: "age" },
  { mot: "agence", genre: "féminin", sig: "agency" },
  { mot: "agent", genre: "masculin", sig: "agent" },
  { mot: "agneau", genre: "masculin", sig: "lamb" },
  { mot: "aide", genre: "féminin", sig: "aid" },
  { mot: "aiguille", genre: "féminin", sig: "needle" },
  { mot: "air", genre: "masculin", sig: "air" },
  { mot: "alarme", genre: "féminin", sig: "alarm" },
  { mot: "album", genre: "masculin", sig: "album" },
  { mot: "alcool", genre: "masculin", sig: "alcohol" },
  { mot: "alimentation", genre: "féminin", sig: "feed" },
  { mot: "allemand", genre: "masculin", sig: "german (the language)" },
  { mot: "alliance", genre: "féminin", sig: "alliance" },
  { mot: "allié", genre: "masculin", sig: "ally" },
  { mot: "alternative", genre: "féminin", sig: "alternative" },
  { mot: "ambassade", genre: "féminin", sig: "embassy" },
  { mot: "ambulance", genre: "féminin", sig: "ambulance" },
  { mot: "âme", genre: "féminin", sig: "soul" },
  { mot: "ami", genre: "masculin", sig: "friend (male)" },
  { mot: "amie", genre: "féminin", sig: "friend (female)" },
  { mot: "amitié", genre: "féminin", sig: "friendship" },
  { mot: "amour", genre: "masculin", sig: "love" },
  { mot: "amusement", genre: "masculin", sig: "fun" },
  { mot: "an", genre: "masculin", sig: "year" },
  { mot: "analyse", genre: "féminin", sig: "analysis" },
  { mot: "âne", genre: "masculin", sig: "donkey" },
  { mot: "ange", genre: "masculin", sig: "angel" },
  { mot: "anglais", genre: "masculin", sig: "english (the language)" },
  { mot: "angle", genre: "masculin", sig: "angle" },
  { mot: "animal", genre: "masculin", sig: "animal" },
  { mot: "animal de compagnie", genre: "masculin", sig: "pet" },
  { mot: "année", genre: "féminin", sig: "year" },
  { mot: "anniversaire", genre: "masculin", sig: "birthday; anniversary" },
  { mot: "annonce", genre: "féminin", sig: "announcement" },
  { mot: "appareil photo", genre: "masculin", sig: "camera" },
  { mot: "apparence", genre: "féminin", sig: "appearance" },
  { mot: "appartement", genre: "masculin", sig: "apartment" },
  { mot: "appât", genre: "masculin", sig: "bait" },
  { mot: "appel", genre: "masculin", sig: "call; appeal" },
  { mot: "appétit", genre: "masculin", sig: "appetite" },
  { mot: "applaudissements", genre: "masculin", sig: "applause" },
  { mot: "approche", genre: "féminin", sig: "approach" },
  { mot: "approvisionnement", genre: "masculin", sig: "supply" },
  { mot: "après-midi", genre: "masculin", sig: "afternoon" },
  { mot: "araignée", genre: "féminin", sig: "spider" },
  { mot: "arbre", genre: "masculin", sig: "tree" },
  { mot: "arc", genre: "masculin", sig: "bow" },
  { mot: "arc-en-ciel", genre: "masculin", sig: "rainbow" },
  { mot: "argent", genre: "masculin", sig: "money; silver" },
  { mot: "argent liquide", genre: "masculin", sig: "cash" },
  { mot: "argument", genre: "masculin", sig: "argument" },
  { mot: "arme", genre: "féminin", sig: "weapon" },
  { mot: "armée", genre: "féminin", sig: "army" },
  { mot: "armoire", genre: "féminin", sig: "cabinet" },
  { mot: "arrangement", genre: "masculin", sig: "arrangement" },
  { mot: "arrestation", genre: "féminin", sig: "arrest" },
  { mot: "arrêt", genre: "masculin", sig: "stop; halt" },
  { mot: "arrière", genre: "masculin", sig: "rear" },
  { mot: "arrière-plan", genre: "masculin", sig: "background" },
  { mot: "arrivée", genre: "féminin", sig: "arrival" },
  { mot: "art", genre: "masculin", sig: "art" },
  { mot: "article", genre: "masculin", sig: "article; item" },
  { mot: "ascenseur", genre: "masculin", sig: "lift; elevator" },
  { mot: "assaut", genre: "masculin", sig: "assault" },
  { mot: "assiette", genre: "féminin", sig: "plate" },
  { mot: "assistance", genre: "féminin", sig: "assistance" },
  { mot: "assurance", genre: "féminin", sig: "insurance" },
  { mot: "astuce", genre: "féminin", sig: "trick" },
  { mot: "atmosphère", genre: "féminin", sig: "atmosphere" },
  { mot: "attaque", genre: "féminin", sig: "attack; stroke (medical)" },
  { mot: "attention", genre: "féminin", sig: "attention" },
  { mot: "attitude", genre: "féminin", sig: "attitude" },
  { mot: "aube", genre: "féminin", sig: "dawn" },
  { mot: "augmentation", genre: "féminin", sig: "increase" },
  { mot: "auteur", genre: "masculin", sig: "author" },
  { mot: "autochtone", genre: "masculin", sig: "native" },
  { mot: "autopsie", genre: "féminin", sig: "autopsy" },
  { mot: "autorité", genre: "féminin", sig: "authority" },
  { mot: "autres", genre: "masculin", sig: "others" },
  { mot: "avance", genre: "féminin", sig: "advance" },
  { mot: "avantage", genre: "masculin", sig: "advantage; benefit" },
  { mot: "avenir", genre: "masculin", sig: "future" },
  { mot: "aventure", genre: "féminin", sig: "adventure" },
  { mot: "aveu", genre: "masculin", sig: "confession" },
  { mot: "avion", genre: "masculin", sig: "plane; airplane" },
  { mot: "avis", genre: "masculin", sig: "notice" },
  { mot: "avocat", genre: "masculin", sig: "lawyer; attorney" },
  { mot: "bacon", genre: "masculin", sig: "bacon" },
  { mot: "bagage", genre: "masculin", sig: "luggage" },
  { mot: "bague", genre: "féminin", sig: "ring" },
  { mot: "baignoire", genre: "féminin", sig: "bathtub" },
  { mot: "bain", genre: "masculin", sig: "bath" },
  { mot: "baleine", genre: "féminin", sig: "whale" },
  { mot: "balle", genre: "féminin", sig: "ball; bullet" },
  { mot: "ballon", genre: "masculin", sig: "balloon" },
  { mot: "banane", genre: "féminin", sig: "banana" },
  { mot: "banc", genre: "masculin", sig: "bench" },
  { mot: "bande", genre: "féminin", sig: "tape; strip" },
  { mot: "bande dessinée", genre: "féminin", sig: "comic (strip)" },
  { mot: "bang", genre: "masculin", sig: "bang" },
  { mot: "banque", genre: "féminin", sig: "bank" },
  { mot: "bar", genre: "masculin", sig: "bar" },
  { mot: "barbe", genre: "féminin", sig: "beard" },
  { mot: "bas", genre: "masculin", sig: "low" },
  { mot: "base", genre: "féminin", sig: "base; basis" },
  { mot: "baseball", genre: "masculin", sig: "baseball" },
  { mot: "basketball", genre: "masculin", sig: "basketball" },
  { mot: "basse", genre: "féminin", sig: "bass" },
  { mot: "bataille", genre: "féminin", sig: "battle" },
  { mot: "bateau", genre: "masculin", sig: "boat" },
  { mot: "batiment", genre: "masculin", sig: "building" },
  { mot: "bâton", genre: "masculin", sig: "stick" },
  { mot: "batterie", genre: "féminin", sig: "battery" },
  { mot: "bavardage", genre: "masculin", sig: "chatter; chatting; yapping" },
  { mot: "beauté", genre: "féminin", sig: "beauty" },
  { mot: "bébé", genre: "masculin", sig: "baby" },
  { mot: "béguin", genre: "masculin", sig: "crush" },
  { mot: "berger", genre: "masculin", sig: "shepherd" },
  { mot: "besoin", genre: "masculin", sig: "need; requirement" },
  { mot: "bétail", genre: "masculin", sig: "cattle" },
  { mot: "bête", genre: "féminin", sig: "beast" },
  { mot: "béton", genre: "masculin", sig: "concrete" },
  { mot: "beurre", genre: "masculin", sig: "butter" },
  { mot: "bible", genre: "féminin", sig: "bible" },
  { mot: "bibliothèque", genre: "féminin", sig: "library" },
  { mot: "bienvenue", genre: "féminin", sig: "welcome" },
  { mot: "bière", genre: "féminin", sig: "beer" },
  { mot: "bijoux", genre: "masculin", sig: "jewelry" },
  { mot: "billet", genre: "masculin", sig: "ticket" },
  { mot: "bingo", genre: "masculin", sig: "bingo" },
  { mot: "bip", genre: "masculin", sig: "beep (sound)" },
  { mot: "biscuit", genre: "masculin", sig: "cookie" },
  { mot: "blague", genre: "féminin", sig: "joke" },
  { mot: "blâme", genre: "masculin", sig: "blame" },
  { mot: "blessure", genre: "féminin", sig: "wound; injury" },
  { mot: "bloc", genre: "masculin", sig: "block" },
  { mot: "blonde", genre: "féminin", sig: "blonde; woman (girlfriend)" },
  { mot: "bœuf", genre: "masculin", sig: "beef" },
  { mot: "bois", genre: "masculin", sig: "wood" },
  { mot: "boisson", genre: "féminin", sig: "drink" },
  { mot: "boîte", genre: "féminin", sig: "box" },
  { mot: "bol", genre: "masculin", sig: "bowl" },
  { mot: "bombe", genre: "féminin", sig: "bomb" },
  { mot: "bonbon", genre: "masculin", sig: "candy" },
  { mot: "bonheur", genre: "masculin", sig: "happiness" },
  { mot: "bonne affaire", genre: "féminin", sig: "bargain" },
  { mot: "bonté", genre: "féminin", sig: "goodness" },
  { mot: "boom", genre: "masculin", sig: "boom" },
  { mot: "bord", genre: "masculin", sig: "edge" },
  { mot: "bosse", genre: "féminin", sig: "bump" },
  { mot: "botte", genre: "féminin", sig: "boot" },
  { mot: "bouche", genre: "féminin", sig: "mouth" },
  { mot: "boucher", genre: "masculin", sig: "butcher" },
  { mot: "bouchon", genre: "masculin", sig: "plug" },
  { mot: "bouclier", genre: "masculin", sig: "shield" },
  { mot: "bougie", genre: "féminin", sig: "candle" },
  { mot: "boulanger", genre: "masculin", sig: "baker" },
  { mot: "bourse", genre: "féminin", sig: "grant; scholarship; stock exchange; purse" },
  { mot: "bouteille", genre: "féminin", sig: "bottle" },
  { mot: "boutique", genre: "féminin", sig: "shop" },
  { mot: "bouton", genre: "masculin", sig: "button" },
  { mot: "branche", genre: "féminin", sig: "branch" },
  { mot: "bras", genre: "masculin", sig: "arm" },
  { mot: "brique", genre: "féminin", sig: "brick" },
  { mot: "briquet", genre: "masculin", sig: "lighter" },
  { mot: "brise", genre: "féminin", sig: "breeze" },
  { mot: "brosse", genre: "féminin", sig: "brush" },
  { mot: "bruit", genre: "masculin", sig: "noise" },
  { mot: "brûlure", genre: "féminin", sig: "burn" },
  { mot: "brun", genre: "masculin", sig: "brown" },
  { mot: "brute", genre: "féminin", sig: "bully" },
  { mot: "bûche", genre: "féminin", sig: "log" },
  { mot: "budget", genre: "masculin", sig: "budget" },
  { mot: "bulle", genre: "féminin", sig: "bubble" },
  { mot: "bureau", genre: "masculin", sig: "office; desk" },
  { mot: "bus", genre: "masculin", sig: "bus" },
  { mot: "but", genre: "masculin", sig: "purpose; goal" },
  { mot: "cabane", genre: "féminin", sig: "cabin; hut; booth" },
  { mot: "câble", genre: "masculin", sig: "cable" },
  { mot: "cache", genre: "féminin", sig: "hiding place" },
  { mot: "cadavre", genre: "masculin", sig: "corpse" },
  { mot: "cadeau", genre: "masculin", sig: "gift" },
  { mot: "cadenas", genre: "masculin", sig: "(pad)lock" },
  { mot: "cadre", genre: "masculin", sig: "frame" },
  { mot: "café", genre: "masculin", sig: "coffee; café" },
  { mot: "cage", genre: "féminin", sig: "cage" },
  { mot: "calme", genre: "masculin", sig: "calm" },
  { mot: "camarade", genre: "masculin", sig: "fellow; comrade" },
  { mot: "camion", genre: "masculin", sig: "truck" },
  { mot: "camp", genre: "masculin", sig: "camp" },
  { mot: "campagne", genre: "féminin", sig: "campaign" },
  { mot: "campus", genre: "masculin", sig: "campus" },
  { mot: "canal", genre: "masculin", sig: "channel" },
  { mot: "canapé", genre: "masculin", sig: "couch" },
  { mot: "canard", genre: "masculin", sig: "duck" },
  { mot: "cancer", genre: "masculin", sig: "cancer" },
  { mot: "candidat", genre: "masculin", sig: "candidate" },
  { mot: "canon", genre: "masculin", sig: "cannon" },
  { mot: "caoutchouc", genre: "masculin", sig: "rubber" },
  { mot: "capacité", genre: "féminin", sig: "ability" },
  { mot: "capitaine", genre: "masculin", sig: "captain" },
  { mot: "capital", genre: "masculin", sig: "capital" },
  { mot: "capot", genre: "masculin", sig: "hood" },
  { mot: "capture", genre: "féminin", sig: "catch" },
  { mot: "caractère", genre: "masculin", sig: "character" },
  { mot: "caractéristique", genre: "féminin", sig: "feature; trait; attribute" },
  { mot: "carburant", genre: "masculin", sig: "fuel" },
  { mot: "carré", genre: "masculin", sig: "square" },
  { mot: "carrière", genre: "féminin", sig: "career" },
  { mot: "carte", genre: "féminin", sig: "card; map" },
  { mot: "cas", genre: "masculin", sig: "case; matter; circumstance" },
  { mot: "casier", genre: "masculin", sig: "locker" },
  { mot: "casino", genre: "masculin", sig: "casino" },
  { mot: "casque", genre: "masculin", sig: "helmet" },
  { mot: "casquette", genre: "féminin", sig: "cap" },
  { mot: "cauchemar", genre: "masculin", sig: "nightmare" },
  { mot: "cause", genre: "féminin", sig: "cause" },
  { mot: "caution", genre: "féminin", sig: "bail" },
  { mot: "cave", genre: "féminin", sig: "cellar" },
  { mot: "ceinture", genre: "féminin", sig: "belt" },
  { mot: "ceinture de sécurité", genre: "féminin", sig: "seatbelt" },
  { mot: "célébration", genre: "féminin", sig: "celebration" },
  { mot: "célébrité", genre: "féminin", sig: "celebrity" },
  { mot: "cellule", genre: "féminin", sig: "cell" },
  { mot: "cendre", genre: "féminin", sig: "ash" },
  { mot: "centime", genre: "masculin", sig: "cent; penny; 1/100th of a dollar" },
  { mot: "centre", genre: "masculin", sig: "center" },
  { mot: "centre commercial", genre: "masculin", sig: "shopping center" },
  { mot: "cercle", genre: "masculin", sig: "circle" },
  { mot: "cercueil", genre: "masculin", sig: "coffin" },
  { mot: "cérémonie", genre: "féminin", sig: "ceremony" },
  { mot: "cerf", genre: "masculin", sig: "deer" },
  { mot: "cerise", genre: "féminin", sig: "cherry" },
  { mot: "certificat", genre: "masculin", sig: "certificate" },
  { mot: "cerveau", genre: "masculin", sig: "brain" },
  { mot: "chagrin", genre: "masculin", sig: "grief; sorrow" },
  { mot: "chaîne", genre: "féminin", sig: "chain; channel (YouTube, etc.)" },
  { mot: "chair", genre: "féminin", sig: "flesh" },
  { mot: "chaise", genre: "féminin", sig: "chair" },
  { mot: "chaleur", genre: "féminin", sig: "heat" },
  { mot: "chambre", genre: "féminin", sig: "room; bedroom; chamber" },
  { mot: "champ", genre: "masculin", sig: "field" },
  { mot: "champagne", genre: "masculin", sig: "champagne" },
  { mot: "champignon", genre: "masculin", sig: "mushroom; fungus" },
  { mot: "champion", genre: "masculin", sig: "champion" },
  { mot: "chance", genre: "féminin", sig: "luck; chance" },
  { mot: "changement", genre: "masculin", sig: "change; shift" },
  { mot: "chanson", genre: "féminin", sig: "song" },
  { mot: "chaos", genre: "masculin", sig: "chaos" },
  { mot: "chapeau", genre: "masculin", sig: "hat" },
  { mot: "chapitre", genre: "masculin", sig: "chapter" },
  { mot: "charbon", genre: "masculin", sig: "coal" },
  { mot: "charge", genre: "féminin", sig: "charge; load" },
  { mot: "chariot", genre: "masculin", sig: "wagon; cart" },
  { mot: "charme", genre: "masculin", sig: "charm" },
  { mot: "chat", genre: "masculin", sig: "cat; chat" },
  { mot: "château", genre: "masculin", sig: "castle" },
  { mot: "chaussure", genre: "féminin", sig: "shoe" },
  { mot: "chauve-souris", genre: "féminin", sig: "bat" },
  { mot: "chef", genre: "masculin", sig: "boss; chief; leader; chef; friend (sarcastic)" },
  { mot: "chemin", genre: "masculin", sig: "path" },
  { mot: "chemise", genre: "féminin", sig: "shirt" },
  { mot: "chèque", genre: "masculin", sig: "check" },
  { mot: "cheval", genre: "masculin", sig: "horse" },
  { mot: "cheveux", genre: "masculin", sig: "hair" },
  { mot: "chèvre", genre: "féminin", sig: "goat" },
  { mot: "chien", genre: "masculin", sig: "dog" },
  { mot: "chiffre", genre: "masculin", sig: "digit; number; figure" },
  { mot: "chiot", genre: "masculin", sig: "puppy" },
  { mot: "chirurgie", genre: "féminin", sig: "surgery" },
  { mot: "choc", genre: "masculin", sig: "shock" },
  { mot: "chocolat", genre: "masculin", sig: "chocolate" },
  { mot: "choix", genre: "masculin", sig: "choice; pick" },
  { mot: "chose", genre: "féminin", sig: "thing" },
  { mot: "chose(s)", genre: "féminin", sig: "thing; stuff" },
  { mot: "chute", genre: "féminin", sig: "fall" },
  { mot: "cible", genre: "féminin", sig: "target" },
  { mot: "cicatrice", genre: "féminin", sig: "scar" },
  { mot: "ciel", genre: "masculin", sig: "sky" },
  { mot: "cigarette", genre: "féminin", sig: "cigarette" },
  { mot: "cimetière", genre: "masculin", sig: "cemetery" },
  { mot: "cinéma", genre: "masculin", sig: "cinema" },
  { mot: "cintre", genre: "masculin", sig: "(coat)hanger" },
  { mot: "circonstance", genre: "féminin", sig: "circumstance" },
  { mot: "circulation", genre: "féminin", sig: "traffic" },
  { mot: "cirque", genre: "masculin", sig: "circus" },
  { mot: "citation", genre: "féminin", sig: "quote" },
  { mot: "citron", genre: "masculin", sig: "lemon" },
  { mot: "civilisation", genre: "féminin", sig: "civilization" },
  { mot: "classe", genre: "féminin", sig: "class" },
  { mot: "classique", genre: "masculin", sig: "classic" },
  { mot: "clé", genre: "féminin", sig: "key" },
  { mot: "clic", genre: "masculin", sig: "click" },
  { mot: "client", genre: "masculin", sig: "client; customer" },
  { mot: "clinique", genre: "féminin", sig: "clinic" },
  { mot: "cloche", genre: "féminin", sig: "bell" },
  { mot: "clôture", genre: "féminin", sig: "fence; enclosure" },
  { mot: "clou", genre: "masculin", sig: "nail" },
  { mot: "club", genre: "masculin", sig: "club" },
  { mot: "cochon", genre: "masculin", sig: "pig" },
  { mot: "cocktail", genre: "masculin", sig: "cocktail" },
  { mot: "code", genre: "masculin", sig: "code" },
  { mot: "cœur", genre: "masculin", sig: "heart" },
  { mot: "coffre-fort", genre: "masculin", sig: "safe; safety deposit box; lockbox" },
  { mot: "coin", genre: "masculin", sig: "corner" },
  { mot: "coïncidence", genre: "féminin", sig: "coincidence" },
  { mot: "col", genre: "masculin", sig: "collar" },
  { mot: "colère", genre: "féminin", sig: "anger" },
  { mot: "colle", genre: "féminin", sig: "glue; paste; adhesive" },
  { mot: "collection", genre: "féminin", sig: "collection" },
  { mot: "collège", genre: "masculin", sig: "college" },
  { mot: "collègue", genre: "masculin", sig: "colleague" },
  { mot: "collier", genre: "masculin", sig: "necklace" },
  { mot: "colline", genre: "féminin", sig: "hill" },
  { mot: "colonne", genre: "féminin", sig: "column; spine" },
  { mot: "coma", genre: "masculin", sig: "coma" },
  { mot: "combat", genre: "masculin", sig: "fight; combat" },
  { mot: "combinaison", genre: "féminin", sig: "combination" },
  { mot: "comédie", genre: "féminin", sig: "comedy" },
  { mot: "comité", genre: "masculin", sig: "committee" },
  { mot: "commande", genre: "féminin", sig: "command" },
  { mot: "commentaire", genre: "masculin", sig: "comment" },
  { mot: "commerce", genre: "masculin", sig: "trade" },
  { mot: "communauté", genre: "féminin", sig: "community" },
  { mot: "communication", genre: "féminin", sig: "communication" },
  { mot: "compagnon", genre: "masculin", sig: "companion; partner (domestic)" },
  { mot: "compétence", genre: "féminin", sig: "skill" },
  { mot: "compétition", genre: "féminin", sig: "competition" },
  { mot: "compliment", genre: "masculin", sig: "compliment" },
  { mot: "complot", genre: "masculin", sig: "plot" },
  { mot: "comportement", genre: "masculin", sig: "behavior" },
  { mot: "compte", genre: "masculin", sig: "count; account" },
  { mot: "comptoir", genre: "masculin", sig: "counter" },
  { mot: "concept", genre: "masculin", sig: "concept" },
  { mot: "conception", genre: "féminin", sig: "design" },
  { mot: "concert", genre: "masculin", sig: "concert" },
  { mot: "conclusion", genre: "féminin", sig: "conclusion" },
  { mot: "concours", genre: "masculin", sig: "contest" },
  { mot: "condition", genre: "féminin", sig: "condition" },
  { mot: "conducteur", genre: "masculin", sig: "driver" },
  { mot: "conférence", genre: "féminin", sig: "conference; lecture" },
  { mot: "confiance", genre: "féminin", sig: "trust; confidence" },
  { mot: "confiture", genre: "féminin", sig: "jam" },
  { mot: "conflit", genre: "masculin", sig: "conflict" },
  { mot: "confort", genre: "masculin", sig: "comfort" },
  { mot: "confusion", genre: "féminin", sig: "confusion" },
  { mot: "connaissance", genre: "féminin", sig: "knowledge" },
  { mot: "connexion", genre: "féminin", sig: "connection" },
  { mot: "conseil", genre: "masculin", sig: "advice; counsel" },
  { mot: "consentement", genre: "masculin", sig: "consent" },
  { mot: "construction", genre: "féminin", sig: "construction; build" },
  { mot: "contact", genre: "masculin", sig: "contact" },
  { mot: "conte", genre: "masculin", sig: "tale" },
  { mot: "contenant", genre: "masculin", sig: "container" },
  { mot: "contenu", genre: "masculin", sig: "content" },
  { mot: "contraire", genre: "masculin", sig: "contrary" },
  { mot: "contrat", genre: "masculin", sig: "contract" },
  { mot: "contrôle", genre: "masculin", sig: "control; test" },
  { mot: "conversation", genre: "féminin", sig: "conversation" },
  { mot: "copain", genre: "masculin", sig: "boyfriend; (male) friend" },
  { mot: "copie", genre: "féminin", sig: "copy" },
  { mot: "copine", genre: "féminin", sig: "girlfriendl (female) friend" },
  { mot: "coq", genre: "masculin", sig: "cock (male chicken)" },
  { mot: "coquille", genre: "féminin", sig: "shell" },
  { mot: "corde", genre: "féminin", sig: "rope" },
  { mot: "corne", genre: "féminin", sig: "horn" },
  { mot: "corps", genre: "masculin", sig: "body; corps (institutional)" },
  { mot: "costume", genre: "masculin", sig: "suit; costume" },
  { mot: "côte", genre: "féminin", sig: "coast" },
  { mot: "côté", genre: "masculin", sig: "side" },
  { mot: "coton", genre: "masculin", sig: "cotton" },
  { mot: "cou", genre: "masculin", sig: "neck" },
  { mot: "coucher de soleil", genre: "masculin", sig: "sunset" },
  { mot: "couleur", genre: "féminin", sig: "color" },
  { mot: "coup", genre: "masculin", sig: "hit; shot; blow; knock; punch; chop" },
  { mot: "couple", genre: "masculin", sig: "couple" },
  { mot: "coupure", genre: "féminin", sig: "cut" },
  { mot: "courage", genre: "masculin", sig: "courage" },
  { mot: "courant", genre: "masculin", sig: "current (liquid or electrical)" },
  { mot: "courbe", genre: "féminin", sig: "bend" },
  { mot: "couronne", genre: "féminin", sig: "crown" },
  { mot: "courrier", genre: "masculin", sig: "mail" },
  { mot: "cours", genre: "masculin", sig: "course" },
  { mot: "cours d'eau", genre: "masculin", sig: "stream" },
  { mot: "course", genre: "féminin", sig: "race" },
  { mot: "coût", genre: "masculin", sig: "cost" },
  { mot: "couteau", genre: "masculin", sig: "knife" },
  { mot: "couverture", genre: "féminin", sig: "cover; blanket" },
  { mot: "crâne", genre: "masculin", sig: "skull" },
  { mot: "crash", genre: "masculin", sig: "crash" },
  { mot: "cravate", genre: "féminin", sig: "tie" },
  { mot: "création", genre: "féminin", sig: "creation" },
  { mot: "créature", genre: "féminin", sig: "creature" },
  { mot: "crédit", genre: "masculin", sig: "credit" },
  { mot: "crème", genre: "féminin", sig: "cream" },
  { mot: "crétin", genre: "masculin", sig: "moron" },
  { mot: "cri", genre: "masculin", sig: "cry; scream; shout; yell" },
  { mot: "crime", genre: "masculin", sig: "crime" },
  { mot: "crise", genre: "féminin", sig: "crisis; attack (medical)" },
  { mot: "critique", genre: "féminin", sig: "review" },
  { mot: "crochet", genre: "masculin", sig: "hook" },
  { mot: "croisière", genre: "féminin", sig: "cruise" },
  { mot: "croix", genre: "féminin", sig: "cross" },
  { mot: "croyance", genre: "féminin", sig: "belief" },
  { mot: "cuir", genre: "masculin", sig: "leather" },
  { mot: "cuisine", genre: "féminin", sig: "kitchen; cooking; cuisine" },
  { mot: "cuivre", genre: "masculin", sig: "copper" },
  { mot: "culpabilité", genre: "féminin", sig: "guilt" },
  { mot: "culte", genre: "masculin", sig: "worship" },
  { mot: "culture", genre: "féminin", sig: "culture" },
  { mot: "cure", genre: "féminin", sig: "cure" },
  { mot: "cycle", genre: "masculin", sig: "cycle" },
  { mot: "dame", genre: "féminin", sig: "lady" },
  { mot: "danger", genre: "masculin", sig: "danger" },
  { mot: "danse", genre: "féminin", sig: "dance" },
  { mot: "débat", genre: "masculin", sig: "debate" },
  { mot: "début", genre: "masculin", sig: "beginning; start" },
  { mot: "décharge", genre: "féminin", sig: "dump; discharge" },
  { mot: "déchets", genre: "masculin", sig: "trash; rubbish" },
  { mot: "décision", genre: "féminin", sig: "decision" },
  { mot: "déclaration", genre: "féminin", sig: "statement" },
  { mot: "découverte", genre: "féminin", sig: "discovery" },
  { mot: "déesse", genre: "féminin", sig: "goddess" },
  { mot: "défaite", genre: "féminin", sig: "defeat" },
  { mot: "défense", genre: "féminin", sig: "defense" },
  { mot: "défi", genre: "masculin", sig: "challenge" },
  { mot: "degré", genre: "masculin", sig: "degree" },
  { mot: "déjeuner", genre: "masculin", sig: "lunch" },
  { mot: "délice", genre: "masculin", sig: "delight; delicacy" },
  { mot: "demande", genre: "féminin", sig: "request; demand; question; application" },
  { mot: "démocratie", genre: "féminin", sig: "democracy" },
  { mot: "démon", genre: "masculin", sig: "demon" },
  { mot: "dent", genre: "féminin", sig: "tooth" },
  { mot: "départ", genre: "masculin", sig: "departure" },
  { mot: "département", genre: "masculin", sig: "department" },
  { mot: "dépense", genre: "féminin", sig: "expense; expenditure" },
  { mot: "dépôt", genre: "masculin", sig: "deposit" },
  { mot: "derrière", genre: "masculin", sig: "back (side); butt" },
  { mot: "désastre", genre: "masculin", sig: "disaster" },
  { mot: "description", genre: "féminin", sig: "description" },
  { mot: "désert", genre: "masculin", sig: "desert" },
  { mot: "déshonneur", genre: "masculin", sig: "disgrace" },
  { mot: "désir", genre: "masculin", sig: "desire" },
  { mot: "désordre", genre: "masculin", sig: "mess" },
  { mot: "dessert", genre: "masculin", sig: "dessert" },
  { mot: "dessin", genre: "masculin", sig: "drawing; design; artwork" },
  { mot: "destin", genre: "masculin", sig: "fate; destiny" },
  { mot: "destination", genre: "féminin", sig: "destination" },
  { mot: "destruction", genre: "féminin", sig: "destruction" },
  { mot: "détail", genre: "masculin", sig: "detail" },
  { mot: "détective", genre: "masculin", sig: "detective" },
  { mot: "dette", genre: "féminin", sig: "debt" },
  { mot: "devant", genre: "masculin", sig: "front" },
  { mot: "développement", genre: "masculin", sig: "development" },
  { mot: "devoir", genre: "masculin", sig: "homework; assignment; duty" },
  { mot: "diable", genre: "masculin", sig: "devil" },
  { mot: "diamant", genre: "masculin", sig: "diamond" },
  { mot: "Dieu", genre: "masculin", sig: "God" },
  { mot: "différence", genre: "féminin", sig: "difference" },
  { mot: "difficulté", genre: "féminin", sig: "difficulty" },
  { mot: "diffusion", genre: "féminin", sig: "broadcast; spread" },
  { mot: "dignité", genre: "féminin", sig: "dignity" },
  { mot: "dîner", genre: "masculin", sig: "dinner" },
  { mot: "direction", genre: "féminin", sig: "direction" },
  { mot: "discipline", genre: "féminin", sig: "discipline" },
  { mot: "discours", genre: "masculin", sig: "speech; discourse (conversation)" },
  { mot: "discussion", genre: "féminin", sig: "discussion; talk" },
  { mot: "distance", genre: "féminin", sig: "distance" },
  { mot: "district", genre: "masculin", sig: "district" },
  { mot: "divertissement", genre: "masculin", sig: "entertainment" },
  { mot: "division", genre: "féminin", sig: "division" },
  { mot: "divorce", genre: "masculin", sig: "divorce" },
  { mot: "docteur", genre: "masculin", sig: "doctor" },
  { mot: "document", genre: "masculin", sig: "document" },
  { mot: "doigt", genre: "masculin", sig: "finger" },
  { mot: "dollar", genre: "masculin", sig: "dollar (unit of currency)" },
  { mot: "dommage", genre: "masculin", sig: "damage" },
  { mot: "données", genre: "féminin", sig: "data" },
  { mot: "dossier", genre: "masculin", sig: "file" },
  { mot: "douceur", genre: "féminin", sig: "sweetness; softness" },
  { mot: "douche", genre: "féminin", sig: "shower" },
  { mot: "douleur", genre: "féminin", sig: "pain" },
  { mot: "doute", genre: "masculin", sig: "doubt" },
  { mot: "dragon", genre: "masculin", sig: "dragon" },
  { mot: "drame", genre: "masculin", sig: "drama" },
  { mot: "drap", genre: "masculin", sig: "sheet" },
  { mot: "drapeau", genre: "masculin", sig: "flag" },
  { mot: "drogue", genre: "féminin", sig: "drug" },
  { mot: "droit", genre: "masculin", sig: "right" },
  { mot: "eau", genre: "féminin", sig: "water" },
  { mot: "échange", genre: "masculin", sig: "exchange" },
  { mot: "échantillon", genre: "masculin", sig: "sample" },
  { mot: "échec", genre: "masculin", sig: "failure" },
  { mot: "échecs", genre: "masculin", sig: "chess" },
  { mot: "échelle", genre: "féminin", sig: "scale; ladder" },
  { mot: "éclat", genre: "masculin", sig: "shine" },
  { mot: "école", genre: "féminin", sig: "school" },
  { mot: "économie", genre: "féminin", sig: "economy" },
  { mot: "écran", genre: "masculin", sig: "screen" },
  { mot: "écrivain", genre: "masculin", sig: "writer" },
  { mot: "éducation", genre: "féminin", sig: "education" },
  { mot: "effet", genre: "masculin", sig: "effect" },
  { mot: "effort", genre: "masculin", sig: "effort" },
  { mot: "église", genre: "féminin", sig: "church" },
  { mot: "élection", genre: "féminin", sig: "election" },
  { mot: "électricité", genre: "féminin", sig: "electricity" },
  { mot: "élément", genre: "masculin", sig: "element" },
  { mot: "éléphant", genre: "masculin", sig: "elephant" },
  { mot: "emballage", genre: "masculin", sig: "wrap" },
  { mot: "émotion", genre: "féminin", sig: "emotion" },
  { mot: "emploi", genre: "masculin", sig: "job" },
  { mot: "enchère", genre: "féminin", sig: "bid; auction" },
  { mot: "endroit", genre: "masculin", sig: "place; point" },
  { mot: "énergie", genre: "féminin", sig: "energy" },
  { mot: "enfance", genre: "féminin", sig: "childhood" },
  { mot: "enfant", genre: "masculin", sig: "infant; child" },
  { mot: "enfer", genre: "masculin", sig: "hell" },
  { mot: "engagement", genre: "masculin", sig: "commitment" },
  { mot: "ennemi", genre: "masculin", sig: "enemy" },
  { mot: "enquête", genre: "féminin", sig: "investigation" },
  { mot: "ensemble", genre: "masculin", sig: "set" },
  { mot: "entrée", genre: "féminin", sig: "entrance; entry" },
  { mot: "entrepôt", genre: "masculin", sig: "warehouse" },
  { mot: "entreprise", genre: "féminin", sig: "company; firm; enterprise" },
  { mot: "entretien", genre: "masculin", sig: "interview" },
  { mot: "enveloppe", genre: "féminin", sig: "envelope" },
  { mot: "envie", genre: "féminin", sig: "wish; desire; longing; want" },
  { mot: "environnement", genre: "masculin", sig: "environment" },
  { mot: "épaule", genre: "féminin", sig: "shoulder" },
  { mot: "épée", genre: "féminin", sig: "sword" },
  { mot: "épingle", genre: "féminin", sig: "pin" },
  { mot: "épisode", genre: "masculin", sig: "episode" },
  { mot: "épouse", genre: "féminin", sig: "wife" },
  { mot: "équilibre", genre: "masculin", sig: "balance" },
  { mot: "équipe", genre: "féminin", sig: "team" },
  { mot: "équipement", genre: "masculin", sig: "equipment; gear" },
  { mot: "ère", genre: "féminin", sig: "era" },
  { mot: "erreur", genre: "féminin", sig: "mistake; error" },
  { mot: "escalade", genre: "féminin", sig: "climb" },
  { mot: "escaliers", genre: "masculin", sig: "stairs" },
  { mot: "escroquerie", genre: "féminin", sig: "con" },
  { mot: "espace", genre: "masculin", sig: "space" },
  { mot: "espèce", genre: "féminin", sig: "species" },
  { mot: "espion", genre: "masculin", sig: "spy" },
  { mot: "espoir", genre: "masculin", sig: "hope" },
  { mot: "esprit", genre: "masculin", sig: "mind; spirit" },
  { mot: "est", genre: "masculin", sig: "east" },
  { mot: "estomac", genre: "masculin", sig: "stomach" },
  { mot: "étape", genre: "féminin", sig: "step; stage; leg (of a journey)" },
  { mot: "état", genre: "masculin", sig: "state" },
  { mot: "été", genre: "masculin", sig: "summer" },
  { mot: "éternité", genre: "féminin", sig: "eternity" },
  { mot: "étiquette", genre: "féminin", sig: "tag" },
  { mot: "étirement", genre: "masculin", sig: "stretch" },
  { mot: "étoile", genre: "féminin", sig: "star" },
  { mot: "étude", genre: "féminin", sig: "study" },
  { mot: "évasion", genre: "féminin", sig: "escape" },
  { mot: "événement", genre: "masculin", sig: "event" },
  { mot: "évier", genre: "masculin", sig: "sink" },
  { mot: "examen", genre: "masculin", sig: "exam" },
  { mot: "excitation", genre: "féminin", sig: "excitement" },
  { mot: "excuse", genre: "féminin", sig: "excuse; apology" },
  { mot: "exécution", genre: "féminin", sig: "execution" },
  { mot: "exemple", genre: "masculin", sig: "example; instance" },
  { mot: "exercice", genre: "masculin", sig: "exercise" },
  { mot: "existence", genre: "féminin", sig: "existence" },
  { mot: "expérience", genre: "féminin", sig: "experience" },
  { mot: "expert", genre: "masculin", sig: "expert" },
  { mot: "explication", genre: "féminin", sig: "explanation" },
  { mot: "explosion", genre: "féminin", sig: "explosion; blast; burst" },
  { mot: "expression", genre: "féminin", sig: "expression" },
  { mot: "extérieur", genre: "masculin", sig: "outside; exterior" },
  { mot: "façon", genre: "féminin", sig: "way; manner; method" },
  { mot: "faiblesse", genre: "féminin", sig: "weakness" },
  { mot: "faim", genre: "féminin", sig: "hunger" },
  { mot: "fait", genre: "masculin", sig: "fact" },
  { mot: "falaise", genre: "féminin", sig: "cliff" },
  { mot: "famille", genre: "féminin", sig: "family" },
  { mot: "fantaisie", genre: "féminin", sig: "fantasy" },
  { mot: "fantôme", genre: "masculin", sig: "ghost" },
  { mot: "faute", genre: "féminin", sig: "fault" },
  { mot: "faveur", genre: "féminin", sig: "favor" },
  { mot: "fée", genre: "féminin", sig: "fairy" },
  { mot: "félicitations", genre: "féminin", sig: "congratulations" },
  { mot: "femelle", genre: "féminin", sig: "female" },
  { mot: "femme", genre: "féminin", sig: "woman" },
  { mot: "fenêtre", genre: "féminin", sig: "window" },
  { mot: "fer", genre: "masculin", sig: "iron" },
  { mot: "ferme", genre: "féminin", sig: "farm" },
  { mot: "fermeture", genre: "féminin", sig: "close" },
  { mot: "fermier", genre: "masculin", sig: "farmer" },
  { mot: "fesses", genre: "féminin", sig: "butt" },
  { mot: "festival", genre: "masculin", sig: "festival" },
  { mot: "fête", genre: "féminin", sig: "party; feast" },
  { mot: "feu", genre: "masculin", sig: "fire" },
  { mot: "fierté", genre: "féminin", sig: "pride" },
  { mot: "fièvre", genre: "féminin", sig: "fever" },
  { mot: "figure", genre: "féminin", sig: "figure" },
  { mot: "fil", genre: "masculin", sig: "wire" },
  { mot: "filet", genre: "masculin", sig: "net" },
  { mot: "fille", genre: "féminin", sig: "girl; daughter" },
  { mot: "film", genre: "masculin", sig: "film; movie" },
  { mot: "fils", genre: "masculin", sig: "son" },
  { mot: "fin", genre: "féminin", sig: "end; finish" },
  { mot: "final", genre: "masculin", sig: "final" },
  { mot: "fissure", genre: "féminin", sig: "crack" },
  { mot: "flamme", genre: "féminin", sig: "flame" },
  { mot: "flash", genre: "masculin", sig: "flash" },
  { mot: "flèche", genre: "féminin", sig: "arrow" },
  { mot: "fleur", genre: "féminin", sig: "flower" },
  { mot: "flip", genre: "masculin", sig: "flip" },
  { mot: "flotte", genre: "féminin", sig: "fleet" },
  { mot: "flux", genre: "masculin", sig: "flow" },
  { mot: "focalisation", genre: "féminin", sig: "focus" },
  { mot: "foie", genre: "masculin", sig: "liver" },
  { mot: "fois", genre: "féminin", sig: "time (last, this, next, etc.)" },
  { mot: "folie", genre: "féminin", sig: "madness" },
  { mot: "fonction", genre: "féminin", sig: "function" },
  { mot: "fond", genre: "masculin", sig: "bottom" },
  { mot: "fondation", genre: "féminin", sig: "foundation" },
  { mot: "fonds", genre: "masculin", sig: "fund" },
  { mot: "football", genre: "masculin", sig: "football" },
  { mot: "force", genre: "féminin", sig: "strength; force" },
  { mot: "forêt", genre: "féminin", sig: "forest" },
  { mot: "forme", genre: "féminin", sig: "form; shape" },
  { mot: "formule", genre: "féminin", sig: "formula" },
  { mot: "fortune", genre: "féminin", sig: "fortune" },
  { mot: "fouille", genre: "féminin", sig: "dig" },
  { mot: "foule", genre: "féminin", sig: "crowd; mob" },
  { mot: "four", genre: "masculin", sig: "oven" },
  { mot: "frais", genre: "masculin", sig: "fee" },
  { mot: "français", genre: "masculin", sig: "french (language)" },
  { mot: "frappe", genre: "féminin", sig: "hit; strike; keystroke" },
  { mot: "fraude", genre: "féminin", sig: "fraud" },
  { mot: "frère", genre: "masculin", sig: "brother" },
  { mot: "friandise", genre: "féminin", sig: "treat" },
  { mot: "frisson", genre: "masculin", sig: "chill" },
  { mot: "friture", genre: "féminin", sig: "fry" },
  { mot: "froid", genre: "masculin", sig: "cold" },
  { mot: "fromage", genre: "masculin", sig: "cheese" },
  { mot: "frontière", genre: "féminin", sig: "border" },
  { mot: "fruit", genre: "masculin", sig: "fruit" },
  { mot: "fuite", genre: "féminin", sig: "leak" },
  { mot: "fumée", genre: "féminin", sig: "smoke" },
  { mot: "funérailles", genre: "féminin", sig: "funeral" },
  { mot: "fusil (de chasse)", genre: "masculin", sig: "rifle; shotgun" },
  { mot: "futur", genre: "masculin", sig: "future" },
  { mot: "galaxie", genre: "féminin", sig: "galaxy" },
  { mot: "galerie", genre: "féminin", sig: "gallery" },
  { mot: "gamin", genre: "masculin", sig: "lad" },
  { mot: "gamme", genre: "féminin", sig: "range" },
  { mot: "gang", genre: "masculin", sig: "gang" },
  { mot: "garage", genre: "masculin", sig: "garage" },
  { mot: "garantie", genre: "féminin", sig: "guarantee" },
  { mot: "garçon", genre: "masculin", sig: "boy" },
  { mot: "garde", genre: "féminin", sig: "custody; protection" },
  { mot: "gardien", genre: "masculin", sig: "guardian; custodian" },
  { mot: "gare", genre: "féminin", sig: "station" },
  { mot: "gars", genre: "masculin", sig: "chap" },
  { mot: "gaspillage", genre: "masculin", sig: "waste" },
  { mot: "gâteau", genre: "masculin", sig: "cake" },
  { mot: "gauche", genre: "féminin", sig: "left" },
  { mot: "gaz", genre: "masculin", sig: "gas" },
  { mot: "géant", genre: "masculin", sig: "giant" },
  { mot: "gel", genre: "masculin", sig: "freeze" },
  { mot: "gène", genre: "masculin", sig: "gene" },
  { mot: "génération", genre: "féminin", sig: "generation" },
  { mot: "génie", genre: "masculin", sig: "genius" },
  { mot: "genou", genre: "masculin", sig: "knee" },
  { mot: "genre", genre: "masculin", sig: "gender" },
  { mot: "gentillesse", genre: "féminin", sig: "kindness" },
  { mot: "geste", genre: "masculin", sig: "movement; act; move (of a performace); motion" },
  { mot: "gestion", genre: "féminin", sig: "management" },
  { mot: "gifle", genre: "féminin", sig: "slap" },
  { mot: "gin", genre: "masculin", sig: "gin" },
  { mot: "gingembre", genre: "masculin", sig: "ginger" },
  { mot: "glace", genre: "féminin", sig: "ice" },
  { mot: "golf", genre: "masculin", sig: "golf" },
  { mot: "gomme", genre: "féminin", sig: "gum" },
  { mot: "gonflement", genre: "masculin", sig: "swelling" },
  { mot: "gorge", genre: "féminin", sig: "throat" },
  { mot: "goût", genre: "masculin", sig: "taste" },
  { mot: "goutte", genre: "féminin", sig: "drop" },
  { mot: "gouvernement", genre: "masculin", sig: "government" },
  { mot: "graine", genre: "féminin", sig: "seed" },
  { mot: "graisse", genre: "féminin", sig: "fat" },
  { mot: "grand-mère", genre: "féminin", sig: "grandmother" },
  { mot: "grand-père", genre: "masculin", sig: "grandfather" },
  { mot: "gravité", genre: "féminin", sig: "gravity" },
  { mot: "grec", genre: "masculin", sig: "greek (langauge)" },
  { mot: "grenouille", genre: "féminin", sig: "frog" },
  { mot: "grève", genre: "féminin", sig: "strike (refusal to work)" },
  { mot: "groupe", genre: "masculin", sig: "group; band" },
  { mot: "guerre", genre: "féminin", sig: "war" },
  { mot: "guide", genre: "masculin", sig: "guide" },
  { mot: "guitare", genre: "féminin", sig: "guitar" },
  { mot: "habitude", genre: "féminin", sig: "habit" },
  { mot: "haine", genre: "féminin", sig: "hate; hatred" },
  { mot: "hall", genre: "masculin", sig: "hall; lobby" },
  { mot: "hanche", genre: "féminin", sig: "hip" },
  { mot: "hâte", genre: "féminin", sig: "hurry" },
  { mot: "hausse", genre: "féminin", sig: "rise" },
  { mot: "haut-parleur", genre: "masculin", sig: "speaker" },
  { mot: "hauteur", genre: "féminin", sig: "height" },
  { mot: "hélicoptère", genre: "masculin", sig: "helicopter" },
  { mot: "herbe", genre: "féminin", sig: "grass" },
  { mot: "héros", genre: "masculin", sig: "hero" },
  { mot: "heure", genre: "féminin", sig: "hour; o'clock" },
  { mot: "histoire", genre: "féminin", sig: "story; history" },
  { mot: "hiver", genre: "masculin", sig: "winter" },
  { mot: "hockey", genre: "masculin", sig: "hockey" },
  { mot: "homme", genre: "masculin", sig: "man" },
  { mot: "honnêteté", genre: "féminin", sig: "honesty" },
  { mot: "honneur", genre: "masculin", sig: "honor" },
  { mot: "honte", genre: "féminin", sig: "shame" },
  { mot: "hôpital", genre: "masculin", sig: "hospital" },
  { mot: "horloge", genre: "féminin", sig: "clock" },
  { mot: "horreur", genre: "féminin", sig: "horror" },
  { mot: "hôte", genre: "masculin", sig: "host" },
  { mot: "hôtel", genre: "masculin", sig: "hotel" },
  { mot: "huile", genre: "féminin", sig: "oil" },
  { mot: "humain", genre: "masculin", sig: "human" },
  { mot: "humanité", genre: "féminin", sig: "humanity; mankind" },
  { mot: "humeur", genre: "féminin", sig: "mood" },
  { mot: "humour", genre: "masculin", sig: "humor" },
  { mot: "idée", genre: "féminin", sig: "idea" },
  { mot: "identité", genre: "féminin", sig: "identity" },
  { mot: "idiot", genre: "masculin", sig: "idiot" },
  { mot: "île", genre: "féminin", sig: "island" },
  { mot: "illusion", genre: "féminin", sig: "illusion" },
  { mot: "image", genre: "féminin", sig: "picture; image" },
  { mot: "imagination", genre: "féminin", sig: "imagination" },
  { mot: "importance", genre: "féminin", sig: "importance" },
  { mot: "impression", genre: "féminin", sig: "print; impression" },
  { mot: "incident", genre: "masculin", sig: "incident" },
  { mot: "indice", genre: "masculin", sig: "clue" },
  { mot: "individu", genre: "masculin", sig: "individual" },
  { mot: "industrie", genre: "féminin", sig: "industry" },
  { mot: "infection", genre: "féminin", sig: "infection" },
  { mot: "infirmière", genre: "féminin", sig: "nurse" },
  { mot: "influence", genre: "féminin", sig: "influence" },
  { mot: "information", genre: "féminin", sig: "information" },
  { mot: "ingénieur", genre: "masculin", sig: "engineer" },
  { mot: "inondation", genre: "féminin", sig: "flood" },
  { mot: "inquiétude", genre: "féminin", sig: "worry" },
  { mot: "insecte", genre: "masculin", sig: "bug" },
  { mot: "inspiration", genre: "féminin", sig: "inspiration" },
  { mot: "installation", genre: "féminin", sig: "facility" },
  { mot: "instant", genre: "masculin", sig: "instant" },
  { mot: "instinct", genre: "masculin", sig: "instinct" },
  { mot: "insulte", genre: "féminin", sig: "insult" },
  { mot: "intelligence", genre: "féminin", sig: "intelligence" },
  { mot: "intention", genre: "féminin", sig: "intention" },
  { mot: "intérêt", genre: "masculin", sig: "interest; (for your) sake" },
  { mot: "intérieur", genre: "masculin", sig: "inside" },
  { mot: "internet", genre: "masculin", sig: "internet" },
  { mot: "interrupteur", genre: "masculin", sig: "switch" },
  { mot: "interruption", genre: "féminin", sig: "interrupt" },
  { mot: "intestin", genre: "masculin", sig: "gut" },
  { mot: "intimité", genre: "féminin", sig: "privacy" },
  { mot: "invasion", genre: "féminin", sig: "invasion" },
  { mot: "inversion", genre: "féminin", sig: "reverse" },
  { mot: "investissement", genre: "masculin", sig: "investment" },
  { mot: "invitation", genre: "féminin", sig: "invitation" },
  { mot: "invité", genre: "masculin", sig: "guest" },
  { mot: "jambe", genre: "féminin", sig: "leg" },
  { mot: "jambon", genre: "masculin", sig: "ham" },
  { mot: "jardin", genre: "masculin", sig: "garden" },
  { mot: "jazz", genre: "masculin", sig: "jazz" },
  { mot: "jet", genre: "masculin", sig: "jet" },
  { mot: "jeu", genre: "masculin", sig: "game" },
  { mot: "jeunesse", genre: "féminin", sig: "youth" },
  { mot: "joie", genre: "féminin", sig: "joy" },
  { mot: "joue", genre: "féminin", sig: "cheek" },
  { mot: "jouet", genre: "masculin", sig: "toy" },
  { mot: "jour", genre: "masculin", sig: "day" },
  { mot: "journal", genre: "masculin", sig: "newspaper" },
  { mot: "journal intime", genre: "masculin", sig: "diary" },
  { mot: "journaliste", genre: "masculin", sig: "journalist" },
  { mot: "journée", genre: "féminin", sig: "day; daytime" },
  { mot: "juge", genre: "masculin", sig: "judge" },
  { mot: "jugement", genre: "masculin", sig: "judgment" },
  { mot: "jungle", genre: "féminin", sig: "jungle" },
  { mot: "jupe", genre: "féminin", sig: "skirt" },
  { mot: "jury", genre: "masculin", sig: "jury" },
  { mot: "jus", genre: "masculin", sig: "juice" },
  { mot: "justice", genre: "féminin", sig: "justice" },
  { mot: "kit", genre: "masculin", sig: "kit" },
  { mot: "laboratoire", genre: "masculin", sig: "lab" },
  { mot: "lâche", genre: "masculin", sig: "coward" },
  { mot: "lait", genre: "masculin", sig: "milk" },
  { mot: "lame", genre: "féminin", sig: "blade" },
  { mot: "lampe", genre: "féminin", sig: "lamp" },
  { mot: "langue", genre: "féminin", sig: "language; tongue" },
  { mot: "lapin", genre: "masculin", sig: "rabbit; bunny" },
  { mot: "larme", genre: "féminin", sig: "tear" },
  { mot: "laser", genre: "masculin", sig: "laser" },
  { mot: "lavage", genre: "masculin", sig: "wash" },
  { mot: "leçon", genre: "féminin", sig: "lesson" },
  { mot: "légende", genre: "féminin", sig: "legend" },
  { mot: "lettre", genre: "féminin", sig: "letter" },
  { mot: "lèvre", genre: "féminin", sig: "lip" },
  { mot: "libération", genre: "féminin", sig: "release" },
  { mot: "liberté", genre: "féminin", sig: "freedom; liberty" },
  { mot: "licence", genre: "féminin", sig: "license" },
  { mot: "lien", genre: "masculin", sig: "link" },
  { mot: "lieu", genre: "masculin", sig: "place" },
  { mot: "ligne", genre: "féminin", sig: "line" },
  { mot: "ligue", genre: "féminin", sig: "league" },
  { mot: "limite", genre: "féminin", sig: "limit; bound" },
  { mot: "lion", genre: "masculin", sig: "lion" },
  { mot: "liquide", genre: "masculin", sig: "liquid" },
  { mot: "liste", genre: "féminin", sig: "list" },
  { mot: "lit", genre: "masculin", sig: "bed" },
  { mot: "livraison", genre: "féminin", sig: "delivery" },
  { mot: "livre", genre: "masculin", sig: "book" },
  { mot: "livre", genre: "féminin", sig: "pound (weight; British sterling)" },
  { mot: "local", genre: "masculin", sig: "local" },
  { mot: "loi", genre: "féminin", sig: "law" },
  { mot: "loterie", genre: "féminin", sig: "lottery" },
  { mot: "loup", genre: "masculin", sig: "wolf" },
  { mot: "loyauté", genre: "féminin", sig: "loyalty" },
  { mot: "loyer", genre: "masculin", sig: "rent" },
  { mot: "lumière", genre: "féminin", sig: "light" },
  { mot: "lune", genre: "féminin", sig: "moon" },
  { mot: "lune de miel", genre: "féminin", sig: "honeymoon" },
  { mot: "lutte", genre: "féminin", sig: "struggle" },
  { mot: "luxe", genre: "masculin", sig: "luxury" },
  { mot: "machine", genre: "féminin", sig: "machine" },
  { mot: "madame", genre: "féminin", sig: "madam" },
  { mot: "magasin", genre: "masculin", sig: "store" },
  { mot: "magazine", genre: "masculin", sig: "magazine" },
  { mot: "magie", genre: "féminin", sig: "magic" },
  { mot: "main", genre: "féminin", sig: "hand" },
  { mot: "maire", genre: "masculin", sig: "mayor" },
  { mot: "maïs", genre: "masculin", sig: "corn" },
  { mot: "maison", genre: "féminin", sig: "house; home" },
  { mot: "mal", genre: "masculin", sig: "evil; pain" },
  { mot: "mal de tête", genre: "masculin", sig: "headache" },
  { mot: "maladie", genre: "féminin", sig: "disease; illness" },
  { mot: "mâle", genre: "masculin", sig: "male" },
  { mot: "malédiction", genre: "féminin", sig: "curse" },
  { mot: "maman", genre: "féminin", sig: "mom; mum" },
  { mot: "mamie", genre: "féminin", sig: "granny" },
  { mot: "mandat", genre: "masculin", sig: "warrant" },
  { mot: "manière", genre: "féminin", sig: "manner" },
  { mot: "mannequin", genre: "masculin", sig: "dummy" },
  { mot: "manoir", genre: "masculin", sig: "mansion" },
  { mot: "manque", genre: "masculin", sig: "lack" },
  { mot: "manteau", genre: "masculin", sig: "coat" },
  { mot: "maquillage", genre: "masculin", sig: "makeup" },
  { mot: "marché", genre: "masculin", sig: "market" },
  { mot: "marée", genre: "féminin", sig: "tide" },
  { mot: "mari", genre: "masculin", sig: "husband" },
  { mot: "mariage", genre: "masculin", sig: "marriage" },
  { mot: "marque", genre: "féminin", sig: "brand" },
  { mot: "marteau", genre: "masculin", sig: "hammer" },
  { mot: "masque", genre: "masculin", sig: "mask" },
  { mot: "massage", genre: "masculin", sig: "massage" },
  { mot: "masse", genre: "féminin", sig: "mass" },
  { mot: "match", genre: "masculin", sig: "match" },
  { mot: "matériau", genre: "masculin", sig: "material" },
  { mot: "mathématiques", genre: "féminin", sig: "math" },
  { mot: "matière", genre: "féminin", sig: "material; matter; field; area; subject (area)" },
  { mot: "matin", genre: "masculin", sig: "morning" },
  { mot: "mec", genre: "masculin", sig: "guy" },
  { mot: "médaille", genre: "féminin", sig: "medal" },
  { mot: "médecin", genre: "masculin", sig: "doctor" },
  { mot: "média", genre: "masculin", sig: "media" },
  { mot: "médicament", genre: "masculin", sig: "medicine" },
  { mot: "médication", genre: "féminin", sig: "medication" },
  { mot: "mélange", genre: "masculin", sig: "mix" },
  { mot: "membre", genre: "masculin", sig: "member" },
  { mot: "mémoire", genre: "féminin", sig: "memory" },
  { mot: "menace", genre: "féminin", sig: "threat" },
  { mot: "mensonge", genre: "masculin", sig: "lie" },
  { mot: "mention", genre: "féminin", sig: "mention" },
  { mot: "menton", genre: "masculin", sig: "chin" },
  { mot: "menu", genre: "masculin", sig: "menu" },
  { mot: "mer", genre: "féminin", sig: "sea" },
  { mot: "mère", genre: "féminin", sig: "mother" },
  { mot: "merveille", genre: "féminin", sig: "wonder" },
  { mot: "message", genre: "masculin", sig: "message" },
  { mot: "mesure", genre: "féminin", sig: "measure" },
  { mot: "métal", genre: "masculin", sig: "metal" },
  { mot: "méthode", genre: "féminin", sig: "method" },
  { mot: "métro", genre: "masculin", sig: "subway" },
  { mot: "meuble", genre: "masculin", sig: "furniture" },
  { mot: "meurtre", genre: "masculin", sig: "murder" },
  { mot: "midi", genre: "masculin", sig: "noon" },
  { mot: "milieu", genre: "masculin", sig: "middle" },
  { mot: "minuit", genre: "masculin", sig: "midnight" },
  { mot: "minute", genre: "féminin", sig: "minute" },
  { mot: "miracle", genre: "masculin", sig: "miracle" },
  { mot: "miroir", genre: "masculin", sig: "mirror" },
  { mot: "misère", genre: "féminin", sig: "misery" },
  { mot: "missile", genre: "masculin", sig: "missile" },
  { mot: "mission", genre: "féminin", sig: "mission" },
  { mot: "mode", genre: "féminin", sig: "fashion" },
  { mot: "modèle", genre: "masculin", sig: "model" },
  { mot: "mois", genre: "masculin", sig: "month" },
  { mot: "moitié", genre: "féminin", sig: "half" },
  { mot: "moment", genre: "masculin", sig: "moment" },
  { mot: "monde", genre: "masculin", sig: "world" },
  { mot: "monsieur", genre: "masculin", sig: "gentleman" },
  { mot: "monstre", genre: "masculin", sig: "monster; freak" },
  { mot: "montagne", genre: "féminin", sig: "mountain" },
  { mot: "montant", genre: "masculin", sig: "amount" },
  { mot: "montre", genre: "féminin", sig: "watch" },
  { mot: "morceau", genre: "masculin", sig: "bit" },
  { mot: "mort", genre: "féminin", sig: "death" },
  { mot: "mortel", genre: "masculin", sig: "mortal" },
  { mot: "mot", genre: "masculin", sig: "word" },
  { mot: "motel", genre: "masculin", sig: "motel" },
  { mot: "moteur", genre: "masculin", sig: "engine; motor" },
  { mot: "motif", genre: "masculin", sig: "pattern; motive" },
  { mot: "moto", genre: "féminin", sig: "motorcycle" },
  { mot: "mouche", genre: "féminin", sig: "fly" },
  { mot: "mouchoir", genre: "masculin", sig: "tissue" },
  { mot: "moufette", genre: "féminin", sig: "skunk" },
  { mot: "mouton", genre: "masculin", sig: "sheep" },
  { mot: "mouvement", genre: "masculin", sig: "movement; motion" },
  { mot: "moyenne", genre: "féminin", sig: "average" },
  { mot: "mur", genre: "masculin", sig: "wall" },
  { mot: "muscle", genre: "masculin", sig: "muscle" },
  { mot: "musée", genre: "masculin", sig: "museum" },
  { mot: "musique", genre: "féminin", sig: "music" },
  { mot: "mystère", genre: "masculin", sig: "mystery" },
  { mot: "mythe", genre: "masculin", sig: "myth" },
  { mot: "naissance", genre: "féminin", sig: "birth" },
  { mot: "nation", genre: "féminin", sig: "nation" },
  { mot: "nature", genre: "féminin", sig: "nature" },
  { mot: "navire", genre: "masculin", sig: "ship" },
  { mot: "neige", genre: "féminin", sig: "snow" },
  { mot: "nerf", genre: "masculin", sig: "nerve" },
  { mot: "nettoyage", genre: "masculin", sig: "cleaning" },
  { mot: "neveu", genre: "masculin", sig: "nephew" },
  { mot: "nez", genre: "masculin", sig: "nose" },
  { mot: "nid", genre: "masculin", sig: "nest" },
  { mot: "nièce", genre: "féminin", sig: "niece" },
  { mot: "niveau", genre: "masculin", sig: "level" },
  { mot: "noir", genre: "masculin", sig: "black" },
  { mot: "noix", genre: "féminin", sig: "nut" },
  { mot: "nom", genre: "masculin", sig: "name" },
  { mot: "nombre", genre: "masculin", sig: "number; variety; figure (numerical)" },
  { mot: "nord", genre: "masculin", sig: "north" },
  { mot: "note", genre: "féminin", sig: "note; grade" },
  { mot: "nourriture", genre: "féminin", sig: "food" },
  { mot: "nouvelles", genre: "féminin", sig: "news" },
  { mot: "nuage", genre: "masculin", sig: "cloud" },
  { mot: "nuit", genre: "féminin", sig: "night" },
  { mot: "numéro", genre: "masculin", sig: "number" },
  { mot: "objectif", genre: "masculin", sig: "objective; goal; aim; purpose; target; (camera) lens" },
  { mot: "objet", genre: "masculin", sig: "object" },
  { mot: "obscurité", genre: "féminin", sig: "dark; darkness" },
  { mot: "observation", genre: "féminin", sig: "observation" },
  { mot: "occasion", genre: "féminin", sig: "opportunity; occasion" },
  { mot: "océan", genre: "masculin", sig: "ocean" },
  { mot: "odeur", genre: "féminin", sig: "smell" },
  { mot: "œil", genre: "masculin", sig: "eye" },
  { mot: "œuf", genre: "masculin", sig: "egg" },
  { mot: "offense", genre: "féminin", sig: "offense" },
  { mot: "officiel", genre: "masculin", sig: "official" },
  { mot: "offre", genre: "féminin", sig: "offer" },
  { mot: "oie", genre: "féminin", sig: "goose" },
  { mot: "oiseau", genre: "masculin", sig: "bird" },
  { mot: "ombre", genre: "féminin", sig: "shadow" },
  { mot: "oncle", genre: "masculin", sig: "uncle" },
  { mot: "opéra", genre: "masculin", sig: "opera" },
  { mot: "opération", genre: "féminin", sig: "operation" },
  { mot: "opinion", genre: "féminin", sig: "opinion" },
  { mot: "opportunité", genre: "féminin", sig: "opportunity; opening" },
  { mot: "opposé", genre: "masculin", sig: "opposite" },
  { mot: "option", genre: "féminin", sig: "option" },
  { mot: "or", genre: "masculin", sig: "gold" },
  { mot: "orange", genre: "féminin", sig: "orange" },
  { mot: "orbite", genre: "féminin", sig: "orbit" },
  { mot: "ordinateur", genre: "masculin", sig: "computer" },
  { mot: "ordre", genre: "masculin", sig: "order" },
  { mot: "oreille", genre: "féminin", sig: "ear" },
  { mot: "oreiller", genre: "masculin", sig: "pillow" },
  { mot: "organe", genre: "masculin", sig: "organ" },
  { mot: "organisation", genre: "féminin", sig: "organization" },
  { mot: "orteil (doigt de pied)", genre: "masculin", sig: "toe" },
  { mot: "os", genre: "masculin", sig: "bone" },
  { mot: "otage", genre: "masculin", sig: "hostage" },
  { mot: "ouest", genre: "masculin", sig: "west" },
  { mot: "ours", genre: "masculin", sig: "bear" },
  { mot: "outil", genre: "masculin", sig: "tool" },
  { mot: "oxygène", genre: "masculin", sig: "oxygen" },
  { mot: "page", genre: "féminin", sig: "page" },
  { mot: "paiement", genre: "masculin", sig: "payment" },
  { mot: "pain", genre: "masculin", sig: "bread" },
  { mot: "paire", genre: "féminin", sig: "pair" },
  { mot: "paix", genre: "féminin", sig: "peace" },
  { mot: "palais", genre: "masculin", sig: "palace" },
  { mot: "panier", genre: "masculin", sig: "basket" },
  { mot: "panique", genre: "féminin", sig: "panic" },
  { mot: "papa", genre: "masculin", sig: "dad; father" },
  { mot: "papier", genre: "masculin", sig: "paper" },
  { mot: "paquet", genre: "masculin", sig: "pack; package" },
  { mot: "paradis", genre: "masculin", sig: "heaven; paradise" },
  { mot: "parc", genre: "masculin", sig: "park" },
  { mot: "pardon", genre: "masculin", sig: "pardon; forgiveness" },
  { mot: "parent", genre: "masculin", sig: "parent" },
  { mot: "parfum", genre: "masculin", sig: "perfume; scent" },
  { mot: "pari", genre: "masculin", sig: "bet" },
  { mot: "parole", genre: "féminin", sig: "parole" },
  { mot: "part", genre: "féminin", sig: "share; part" },
  { mot: "partie", genre: "féminin", sig: "part" },
  { mot: "pas", genre: "masculin", sig: "step" },
  { mot: "passage", genre: "masculin", sig: "passage" },
  { mot: "passé", genre: "masculin", sig: "past" },
  { mot: "passeport", genre: "masculin", sig: "passport" },
  { mot: "passion", genre: "féminin", sig: "passion" },
  { mot: "pâte", genre: "féminin", sig: "dough" },
  { mot: "patience", genre: "féminin", sig: "patience" },
  { mot: "patron", genre: "masculin", sig: "boss" },
  { mot: "patrouille", genre: "féminin", sig: "patrol" },
  { mot: "paume", genre: "féminin", sig: "palm" },
  { mot: "pause", genre: "féminin", sig: "break" },
  { mot: "paye", genre: "féminin", sig: "pay(check); salary" },
  { mot: "pays", genre: "masculin", sig: "country" },
  { mot: "peau", genre: "féminin", sig: "skin" },
  { mot: "peinture", genre: "féminin", sig: "paint" },
  { mot: "pénalité", genre: "féminin", sig: "penalty" },
  { mot: "pénis", genre: "masculin", sig: "penis" },
  { mot: "pensée", genre: "féminin", sig: "thought" },
  { mot: "perceuse", genre: "féminin", sig: "drill" },
  { mot: "père", genre: "masculin", sig: "father" },
  { mot: "performance", genre: "féminin", sig: "performance" },
  { mot: "période", genre: "féminin", sig: "period" },
  { mot: "permis", genre: "masculin", sig: "permit" },
  { mot: "permission", genre: "féminin", sig: "permission" },
  { mot: "personnage", genre: "masculin", sig: "character; figure" },
  { mot: "personnalité", genre: "féminin", sig: "personality" },
  { mot: "personne", genre: "féminin", sig: "person" },
  { mot: "personnel", genre: "masculin", sig: "staff; personnel" },
  { mot: "perspective", genre: "féminin", sig: "perspective" },
  { mot: "perte", genre: "féminin", sig: "loss" },
  { mot: "petit ami", genre: "masculin", sig: "boyfriend" },
  { mot: "petit-déjeuner", genre: "masculin", sig: "breakfast" },
  { mot: "petit-fils", genre: "masculin", sig: "grandson" },
  { mot: "petite amie", genre: "féminin", sig: "girlfriend" },
  { mot: "peuple", genre: "masculin", sig: "folk" },
  { mot: "peur", genre: "féminin", sig: "fear" },
  { mot: "phase", genre: "féminin", sig: "phase" },
  { mot: "philosophie", genre: "féminin", sig: "philosophy" },
  { mot: "photo", genre: "féminin", sig: "photo" },
  { mot: "phrase", genre: "féminin", sig: "sentence" },
  { mot: "physique", genre: "féminin", sig: "physics" },
  { mot: "piano", genre: "masculin", sig: "piano" },
  { mot: "pièce", genre: "féminin", sig: "piece" },
  { mot: "pièce (de monnaie)", genre: "féminin", sig: "coin" },
  { mot: "pied", genre: "masculin", sig: "foot" },
  { mot: "piège", genre: "masculin", sig: "trap" },
  { mot: "pierre", genre: "féminin", sig: "stone" },
  { mot: "pilule", genre: "féminin", sig: "pill" },
  { mot: "pique-nique", genre: "masculin", sig: "picnic" },
  { mot: "piqûre", genre: "féminin", sig: "prick (of a needle); injection" },
  { mot: "pirate", genre: "masculin", sig: "pirate" },
  { mot: "piscine", genre: "féminin", sig: "pool" },
  { mot: "piste", genre: "féminin", sig: "track; trail" },
  { mot: "pistolet", genre: "masculin", sig: "gun; pistol" },
  { mot: "pitié", genre: "féminin", sig: "pity" },
  { mot: "pizza", genre: "féminin", sig: "pizza" },
  { mot: "placard", genre: "masculin", sig: "closet" },
  { mot: "place", genre: "féminin", sig: "place" },
  { mot: "plage", genre: "féminin", sig: "beach" },
  { mot: "plainte", genre: "féminin", sig: "complaint" },
  { mot: "plaisir", genre: "masculin", sig: "pleasure" },
  { mot: "plan", genre: "masculin", sig: "plan" },
  { mot: "planche", genre: "féminin", sig: "board" },
  { mot: "planète", genre: "féminin", sig: "planet" },
  { mot: "plante", genre: "féminin", sig: "plant" },
  { mot: "plastique", genre: "masculin", sig: "plastic" },
  { mot: "plat", genre: "masculin", sig: "dish" },
  { mot: "plateforme", genre: "féminin", sig: "platform" },
  { mot: "plomb", genre: "masculin", sig: "lead" },
  { mot: "pluie", genre: "féminin", sig: "rain" },
  { mot: "poche", genre: "féminin", sig: "pocket" },
  { mot: "poêle", genre: "féminin", sig: "pan" },
  { mot: "poème", genre: "masculin", sig: "poem" },
  { mot: "poésie", genre: "féminin", sig: "poetry" },
  { mot: "poids", genre: "masculin", sig: "weight" },
  { mot: "poignée", genre: "féminin", sig: "handle" },
  { mot: "poignet", genre: "masculin", sig: "wrist" },
  { mot: "poing", genre: "masculin", sig: "fist" },
  { mot: "point", genre: "masculin", sig: "point" },
  { mot: "pointe", genre: "féminin", sig: "spike" },
  { mot: "poison", genre: "masculin", sig: "poison" },
  { mot: "poisson", genre: "masculin", sig: "fish" },
  { mot: "poitrine", genre: "féminin", sig: "chest" },
  { mot: "poivre", genre: "masculin", sig: "pepper" },
  { mot: "poker", genre: "masculin", sig: "poker" },
  { mot: "police", genre: "féminin", sig: "police" },
  { mot: "politique", genre: "féminin", sig: "policy; politics" },
  { mot: "pomme", genre: "féminin", sig: "apple" },
  { mot: "pomme de terre (patate)", genre: "féminin", sig: "potato" },
  { mot: "pompe", genre: "féminin", sig: "pump" },
  { mot: "pont", genre: "masculin", sig: "bridge" },
  { mot: "pop", genre: "féminin", sig: "pop" },
  { mot: "population", genre: "féminin", sig: "population" },
  { mot: "porc", genre: "masculin", sig: "pork" },
  { mot: "port", genre: "masculin", sig: "port; harbor" },
  { mot: "portail", genre: "masculin", sig: "gate" },
  { mot: "porte", genre: "féminin", sig: "door" },
  { mot: "portefeuille", genre: "masculin", sig: "wallet" },
  { mot: "position", genre: "féminin", sig: "position" },
  { mot: "possession", genre: "féminin", sig: "possession" },
  { mot: "possibilité", genre: "féminin", sig: "possibility" },
  { mot: "poste", genre: "masculin", sig: "post (work, station)" },
  { mot: "pot", genre: "masculin", sig: "pot" },
  { mot: "poteau", genre: "masculin", sig: "pole" },
  { mot: "potentiel", genre: "masculin", sig: "potential" },
  { mot: "pouce", genre: "masculin", sig: "thumb" },
  { mot: "poudre", genre: "féminin", sig: "powder" },
  { mot: "poulet", genre: "masculin", sig: "chicken" },
  { mot: "poumon", genre: "masculin", sig: "lung" },
  { mot: "pourboire", genre: "masculin", sig: "tip" },
  { mot: "poussière", genre: "féminin", sig: "dust" },
  { mot: "pouvoir", genre: "masculin", sig: "power" },
  { mot: "pratique", genre: "féminin", sig: "practice" },
  { mot: "préjudice", genre: "masculin", sig: "harm" },
  { mot: "préoccupation", genre: "féminin", sig: "concern" },
  { mot: "préparation", genre: "féminin", sig: "preparation; groundwork" },
  { mot: "présence", genre: "féminin", sig: "presence" },
  { mot: "présent", genre: "masculin", sig: "present" },
  { mot: "président", genre: "masculin", sig: "president; chairman" },
  { mot: "pression", genre: "féminin", sig: "pressure" },
  { mot: "prêt", genre: "masculin", sig: "loan" },
  { mot: "preuve", genre: "féminin", sig: "proof; evidence" },
  { mot: "prière", genre: "féminin", sig: "prayer" },
  { mot: "prime", genre: "féminin", sig: "bonus" },
  { mot: "principal", genre: "masculin", sig: "principal" },
  { mot: "principe", genre: "masculin", sig: "principle" },
  { mot: "printemps", genre: "masculin", sig: "spring(time)" },
  { mot: "priorité", genre: "féminin", sig: "priority" },
  { mot: "prise", genre: "féminin", sig: "grip" },
  { mot: "prison", genre: "féminin", sig: "prison; jail" },
  { mot: "prisonnier", genre: "masculin", sig: "prisoner" },
  { mot: "privilège", genre: "masculin", sig: "privilege" },
  { mot: "prix", genre: "masculin", sig: "price; prize; award" },
  { mot: "problème", genre: "masculin", sig: "problem; issue" },
  { mot: "procédure", genre: "féminin", sig: "procedure" },
  { mot: "procès", genre: "masculin", sig: "trial" },
  { mot: "processus", genre: "masculin", sig: "process" },
  { mot: "production", genre: "féminin", sig: "production" },
  { mot: "produit", genre: "masculin", sig: "product" },
  { mot: "produit chimique", genre: "masculin", sig: "chemical" },
  { mot: "professeur", genre: "masculin", sig: "professor" },
  { mot: "profession", genre: "féminin", sig: "profession" },
  { mot: "profil", genre: "masculin", sig: "profile" },
  { mot: "profit", genre: "masculin", sig: "profit" },
  { mot: "programme", genre: "masculin", sig: "program; schedule" },
  { mot: "progrès", genre: "masculin", sig: "progress" },
  { mot: "proie", genre: "féminin", sig: "prey" },
  { mot: "projet", genre: "masculin", sig: "project" },
  { mot: "promenade", genre: "féminin", sig: "walk" },
  { mot: "promesse", genre: "féminin", sig: "promise" },
  { mot: "promotion", genre: "féminin", sig: "promotion" },
  { mot: "proposition", genre: "féminin", sig: "proposal" },
  { mot: "propriété", genre: "féminin", sig: "property" },
  { mot: "protection", genre: "féminin", sig: "protection" },
  { mot: "protestation", genre: "féminin", sig: "protest" },
  { mot: "protocole", genre: "masculin", sig: "protocol" },
  { mot: "pub", genre: "féminin", sig: "ad; publicity" },
  { mot: "public", genre: "masculin", sig: "public; audience" },
  { mot: "publicité", genre: "féminin", sig: "commercial" },
  { mot: "puce", genre: "féminin", sig: "chip" },
  { mot: "punition", genre: "féminin", sig: "punishment" },
  { mot: "puzzle", genre: "masculin", sig: "puzzle" },
  { mot: "qualité", genre: "féminin", sig: "quality" },
  { mot: "quartier", genre: "masculin", sig: "neighborhood; quarter" },
  { mot: "quartier(s) général(s)", genre: "masculin", sig: "headquarters" },
  { mot: "question", genre: "féminin", sig: "question" },
  { mot: "queue", genre: "féminin", sig: "tail" },
  { mot: "racine", genre: "féminin", sig: "root" },
  { mot: "radar", genre: "masculin", sig: "radar" },
  { mot: "radiation", genre: "féminin", sig: "radiation" },
  { mot: "radio", genre: "féminin", sig: "radio" },
  { mot: "rage", genre: "féminin", sig: "rage" },
  { mot: "raid", genre: "masculin", sig: "raid" },
  { mot: "raison", genre: "féminin", sig: "reason; (to be) right" },
  { mot: "rang", genre: "masculin", sig: "rank" },
  { mot: "rangée", genre: "féminin", sig: "row" },
  { mot: "rangement", genre: "masculin", sig: "storage" },
  { mot: "rap", genre: "masculin", sig: "rap" },
  { mot: "rapport", genre: "masculin", sig: "report" },
  { mot: "rat", genre: "masculin", sig: "rat" },
  { mot: "réaction", genre: "féminin", sig: "reaction" },
  { mot: "réalité", genre: "féminin", sig: "reality" },
  { mot: "réception", genre: "féminin", sig: "reception" },
  { mot: "recherche", genre: "féminin", sig: "search; research" },
  { mot: "réclamation", genre: "féminin", sig: "claim" },
  { mot: "récompense", genre: "féminin", sig: "reward" },
  { mot: "récupération", genre: "féminin", sig: "recovery" },
  { mot: "réfrigérateur", genre: "masculin", sig: "fridge" },
  { mot: "regard", genre: "masculin", sig: "stare" },
  { mot: "régime", genre: "masculin", sig: "diet" },
  { mot: "région", genre: "féminin", sig: "area; region" },
  { mot: "règle", genre: "féminin", sig: "rule" },
  { mot: "regret", genre: "masculin", sig: "regret" },
  { mot: "rein", genre: "masculin", sig: "kidney" },
  { mot: "reine", genre: "féminin", sig: "queen" },
  { mot: "relation", genre: "féminin", sig: "relationship" },
  { mot: "religion", genre: "féminin", sig: "religion" },
  { mot: "remarque", genre: "féminin", sig: "note; remark; comment; point" },
  { mot: "remerciement", genre: "masculin", sig: "thanks; gratitude; acknowledgement" },
  { mot: "remorque", genre: "féminin", sig: "trailer" },
  { mot: "rendez-vous", genre: "masculin", sig: "appointment; date" },
  { mot: "réparation", genre: "féminin", sig: "repair; fix" },
  { mot: "repas", genre: "masculin", sig: "meal" },
  { mot: "répétition", genre: "féminin", sig: "rehearsal" },
  { mot: "réponse", genre: "féminin", sig: "answer; response; reply" },
  { mot: "repos", genre: "masculin", sig: "rest" },
  { mot: "réputation", genre: "féminin", sig: "reputation" },
  { mot: "requête", genre: "féminin", sig: "request; query; inquiry; enquiry" },
  { mot: "requin", genre: "masculin", sig: "shark" },
  { mot: "réseau", genre: "masculin", sig: "network" },
  { mot: "réservoir", genre: "masculin", sig: "tank" },
  { mot: "résidence", genre: "féminin", sig: "residence" },
  { mot: "résistance", genre: "féminin", sig: "resistance" },
  { mot: "respect", genre: "masculin", sig: "respect" },
  { mot: "responsabilité", genre: "féminin", sig: "responsibility" },
  { mot: "restaurant", genre: "masculin", sig: "restaurant" },
  { mot: "restes", genre: "masculin", sig: "remains" },
  { mot: "résultat", genre: "masculin", sig: "result" },
  { mot: "retard", genre: "masculin", sig: "delay" },
  { mot: "retour", genre: "masculin", sig: "return" },
  { mot: "retraite", genre: "féminin", sig: "retirement; retreat" },
  { mot: "réunion", genre: "féminin", sig: "metting; reunion" },
  { mot: "rêve", genre: "masculin", sig: "dream" },
  { mot: "réveil", genre: "masculin", sig: "wake" },
  { mot: "révélation", genre: "féminin", sig: "revelation; epiphany; disclosure; spoiler" },
  { mot: "revenu", genre: "masculin", sig: "income" },
  { mot: "révolution", genre: "féminin", sig: "revolution" },
  { mot: "richesse", genre: "féminin", sig: "wealth" },
  { mot: "rideau", genre: "masculin", sig: "curtain" },
  { mot: "rire", genre: "masculin", sig: "laugh; laughter" },
  { mot: "risque", genre: "masculin", sig: "risk" },
  { mot: "rivage", genre: "masculin", sig: "shore" },
  { mot: "rivière", genre: "féminin", sig: "river" },
  { mot: "riz", genre: "masculin", sig: "rice" },
  { mot: "robe", genre: "féminin", sig: "dress" },
  { mot: "robinet", genre: "masculin", sig: "tap" },
  { mot: "robot", genre: "masculin", sig: "robot" },
  { mot: "roche", genre: "féminin", sig: "rock; boulder" },
  { mot: "rocher", genre: "masculin", sig: "rock" },
  { mot: "roi", genre: "masculin", sig: "king" },
  { mot: "rôle", genre: "masculin", sig: "role" },
  { mot: "roman", genre: "masculin", sig: "novel" },
  { mot: "romance", genre: "féminin", sig: "romance" },
  { mot: "rond", genre: "masculin", sig: "circle; ring (shape)" },
  { mot: "rond-point", genre: "masculin", sig: "roundabout" },
  { mot: "rose", genre: "féminin", sig: "pink" },
  { mot: "rotation", genre: "féminin", sig: "spin" },
  { mot: "roue", genre: "féminin", sig: "wheel" },
  { mot: "rouleau", genre: "masculin", sig: "roll" },
  { mot: "route", genre: "féminin", sig: "road; route" },
  { mot: "routine", genre: "féminin", sig: "routine" },
  { mot: "royaume", genre: "masculin", sig: "kingdom" },
  { mot: "rue", genre: "féminin", sig: "street" },
  { mot: "ruine", genre: "féminin", sig: "ruin" },
  { mot: "rumeur", genre: "féminin", sig: "rumor" },
  { mot: "rythme", genre: "masculin", sig: "beat; rhythm" },
  { mot: "sable", genre: "masculin", sig: "sand" },
  { mot: "sac", genre: "masculin", sig: "bag; sack" },
  { mot: "sacrifice", genre: "masculin", sig: "sacrifice" },
  { mot: "sagesse", genre: "féminin", sig: "wisdom" },
  { mot: "saison", genre: "féminin", sig: "season" },
  { mot: "salade", genre: "féminin", sig: "salad" },
  { mot: "salaire", genre: "masculin", sig: "salary" },
  { mot: "saleté", genre: "féminin", sig: "dirt" },
  { mot: "salle", genre: "féminin", sig: "room (shared, for a specific purpose)" },
  { mot: "sandwich", genre: "masculin", sig: "sandwich" },
  { mot: "sang", genre: "masculin", sig: "blood" },
  { mot: "santé", genre: "féminin", sig: "health" },
  { mot: "satellite", genre: "masculin", sig: "satellite" },
  { mot: "sauce", genre: "féminin", sig: "sauce" },
  { mot: "saucisse", genre: "féminin", sig: "sausage" },
  { mot: "saut", genre: "masculin", sig: "jump; hop" },
  { mot: "sauvegarde", genre: "féminin", sig: "backup" },
  { mot: "sauvetage", genre: "masculin", sig: "rescue" },
  { mot: "savon", genre: "masculin", sig: "soap" },
  { mot: "scandale", genre: "masculin", sig: "scandal" },
  { mot: "sceau", genre: "masculin", sig: "seal" },
  { mot: "scénario", genre: "masculin", sig: "script" },
  { mot: "scène", genre: "féminin", sig: "stage; scene" },
  { mot: "science", genre: "féminin", sig: "science" },
  { mot: "score", genre: "masculin", sig: "score" },
  { mot: "scotch", genre: "masculin", sig: "scotch" },
  { mot: "séance", genre: "féminin", sig: "session" },
  { mot: "seau", genre: "masculin", sig: "bucket" },
  { mot: "seconde", genre: "féminin", sig: "second (of time)" },
  { mot: "secret", genre: "masculin", sig: "secret" },
  { mot: "secteur", genre: "masculin", sig: "sector" },
  { mot: "section", genre: "féminin", sig: "section" },
  { mot: "sécurité", genre: "féminin", sig: "safety; security" },
  { mot: "sein", genre: "masculin", sig: "breast" },
  { mot: "sel", genre: "masculin", sig: "salt" },
  { mot: "semaine", genre: "féminin", sig: "week" },
  { mot: "sens", genre: "masculin", sig: "sense" },
  { mot: "sentiment", genre: "masculin", sig: "feel" },
  { mot: "série", genre: "féminin", sig: "series" },
  { mot: "serpent", genre: "masculin", sig: "snake" },
  { mot: "service", genre: "masculin", sig: "service" },
  { mot: "serviette", genre: "féminin", sig: "towel" },
  { mot: "sexe", genre: "masculin", sig: "sex" },
  { mot: "siècle", genre: "masculin", sig: "century" },
  { mot: "siège", genre: "masculin", sig: "seat" },
  { mot: "sieste", genre: "féminin", sig: "nap" },
  { mot: "sifflet", genre: "masculin", sig: "whistle" },
  { mot: "signal", genre: "masculin", sig: "signal" },
  { mot: "signature", genre: "féminin", sig: "signature" },
  { mot: "signe", genre: "masculin", sig: "sign" },
  { mot: "silence", genre: "masculin", sig: "silence" },
  { mot: "singe", genre: "masculin", sig: "monkey" },
  { mot: "sirène", genre: "féminin", sig: "siren" },
  { mot: "site", genre: "masculin", sig: "site" },
  { mot: "situation", genre: "féminin", sig: "situation" },
  { mot: "société", genre: "féminin", sig: "society" },
  { mot: "soeur", genre: "féminin", sig: "sister" },
  { mot: "sœur", genre: "féminin", sig: "sister" },
  { mot: "soi", genre: "masculin", sig: "self" },
  { mot: "soie", genre: "féminin", sig: "silk" },
  { mot: "soin", genre: "masculin", sig: "care; attention" },
  { mot: "soir", genre: "masculin", sig: "evening; night" },
  { mot: "soirée", genre: "féminin", sig: "evening" },
  { mot: "sol", genre: "masculin", sig: "floor; ground; soil" },
  { mot: "soldat", genre: "masculin", sig: "soldier" },
  { mot: "soleil", genre: "masculin", sig: "sun" },
  { mot: "solution", genre: "féminin", sig: "solution" },
  { mot: "somme", genre: "féminin", sig: "sum" },
  { mot: "sommeil", genre: "masculin", sig: "sleep" },
  { mot: "sommet", genre: "masculin", sig: "top" },
  { mot: "son", genre: "masculin", sig: "sound" },
  { mot: "sonnette", genre: "féminin", sig: "doorbell" },
  { mot: "sorte", genre: "féminin", sig: "sort" },
  { mot: "sortie", genre: "féminin", sig: "exit" },
  { mot: "souffle", genre: "masculin", sig: "breath" },
  { mot: "souhait", genre: "masculin", sig: "wish" },
  { mot: "soulagement", genre: "masculin", sig: "relief" },
  { mot: "soupe", genre: "féminin", sig: "soup" },
  { mot: "soupir", genre: "masculin", sig: "sigh" },
  { mot: "source", genre: "féminin", sig: "source" },
  { mot: "sourire", genre: "masculin", sig: "smile" },
  { mot: "souris", genre: "féminin", sig: "mouse" },
  { mot: "sous-sol", genre: "masculin", sig: "basement" },
  { mot: "sous-vêtements", genre: "masculin", sig: "underwear" },
  { mot: "soutien", genre: "masculin", sig: "support" },
  { mot: "soutien-gorge", genre: "masculin", sig: "bra" },
  { mot: "sport", genre: "masculin", sig: "sport" },
  { mot: "standard", genre: "masculin", sig: "standard" },
  { mot: "statue", genre: "féminin", sig: "statue" },
  { mot: "statut", genre: "masculin", sig: "status" },
  { mot: "steak", genre: "masculin", sig: "steak" },
  { mot: "stratégie", genre: "féminin", sig: "strategy" },
  { mot: "stress", genre: "masculin", sig: "stress" },
  { mot: "structure", genre: "féminin", sig: "structure" },
  { mot: "style", genre: "masculin", sig: "style" },
  { mot: "stylo", genre: "masculin", sig: "pen" },
  { mot: "subvention", genre: "féminin", sig: "grant" },
  { mot: "succès", genre: "masculin", sig: "success" },
  { mot: "sucre", genre: "masculin", sig: "sugar" },
  { mot: "sud", genre: "masculin", sig: "south" },
  { mot: "sueur", genre: "féminin", sig: "sweat" },
  { mot: "suggestion", genre: "féminin", sig: "suggestion" },
  { mot: "suite", genre: "féminin", sig: "suite" },
  { mot: "suivi", genre: "masculin", sig: "follow-up; tracking (of location)" },
  { mot: "sujet", genre: "masculin", sig: "subject" },
  { mot: "surface", genre: "féminin", sig: "surface" },
  { mot: "surprise", genre: "féminin", sig: "surprise" },
  { mot: "surveillance", genre: "féminin", sig: "surveillance" },
  { mot: "survie", genre: "féminin", sig: "survival" },
  { mot: "suspect", genre: "masculin", sig: "suspect" },
  { mot: "suspicion", genre: "féminin", sig: "suspicion" },
  { mot: "symbole", genre: "masculin", sig: "symbol" },
  { mot: "sympathie", genre: "féminin", sig: "sympathy" },
  { mot: "syndicat", genre: "masculin", sig: "union" },
  { mot: "système", genre: "masculin", sig: "system" },
  { mot: "table", genre: "féminin", sig: "table" },
  { mot: "tache", genre: "féminin", sig: "spot" },
  { mot: "tâche", genre: "féminin", sig: "task" },
  { mot: "taille", genre: "féminin", sig: "size" },
  { mot: "talent", genre: "masculin", sig: "talent" },
  { mot: "tambour", genre: "masculin", sig: "drum" },
  { mot: "tante", genre: "féminin", sig: "aunt" },
  { mot: "tapis", genre: "masculin", sig: "carpet" },
  { mot: "tarte", genre: "féminin", sig: "pie" },
  { mot: "tas", genre: "masculin", sig: "bunch; pile" },
  { mot: "tasse", genre: "féminin", sig: "cup" },
  { mot: "tatouage", genre: "masculin", sig: "tattoo" },
  { mot: "taupe", genre: "féminin", sig: "mole" },
  { mot: "taureau", genre: "masculin", sig: "bull" },
  { mot: "taux", genre: "masculin", sig: "rate" },
  { mot: "taxe", genre: "féminin", sig: "tax" },
  { mot: "taxi", genre: "masculin", sig: "taxi" },
  { mot: "technique", genre: "féminin", sig: "technique" },
  { mot: "technologie", genre: "féminin", sig: "technology" },
  { mot: "téléphone", genre: "masculin", sig: "(tele)phone" },
  { mot: "télévision", genre: "féminin", sig: "television" },
  { mot: "témoignage", genre: "masculin", sig: "testimony" },
  { mot: "témoin", genre: "masculin", sig: "witness; observer" },
  { mot: "tempérament", genre: "masculin", sig: "temper" },
  { mot: "température", genre: "féminin", sig: "temperature" },
  { mot: "tempête", genre: "féminin", sig: "storm" },
  { mot: "temple", genre: "masculin", sig: "temple" },
  { mot: "temps", genre: "masculin", sig: "weather; time" },
  { mot: "ténèbres", genre: "féminin", sig: "darkness; gloom" },
  { mot: "tennis", genre: "masculin", sig: "tennis" },
  { mot: "tension", genre: "féminin", sig: "tension" },
  { mot: "tentative", genre: "féminin", sig: "attempt" },
  { mot: "tente", genre: "féminin", sig: "tent" },
  { mot: "tenue", genre: "féminin", sig: "outfit" },
  { mot: "terme", genre: "masculin", sig: "term" },
  { mot: "terre", genre: "féminin", sig: "land" },
  { mot: "terreur", genre: "féminin", sig: "terror" },
  { mot: "territoire", genre: "masculin", sig: "territory" },
  { mot: "test", genre: "masculin", sig: "test" },
  { mot: "tête", genre: "féminin", sig: "head" },
  { mot: "texte", genre: "masculin", sig: "text" },
  { mot: "thé", genre: "masculin", sig: "tea" },
  { mot: "théâtre", genre: "masculin", sig: "theater" },
  { mot: "thème", genre: "masculin", sig: "theme" },
  { mot: "théorie", genre: "féminin", sig: "theory" },
  { mot: "thérapie", genre: "féminin", sig: "therapy" },
  { mot: "tige", genre: "féminin", sig: "rod" },
  { mot: "tirage", genre: "masculin", sig: "drawing" },
  { mot: "tiroir", genre: "masculin", sig: "drawer" },
  { mot: "tissu", genre: "masculin", sig: "cloth" },
  { mot: "titre", genre: "masculin", sig: "title" },
  { mot: "toast", genre: "masculin", sig: "toast" },
  { mot: "toilette", genre: "féminin", sig: "toilet" },
  { mot: "toit", genre: "masculin", sig: "roof" },
  { mot: "tombe", genre: "féminin", sig: "grave; tomb" },
  { mot: "ton", genre: "masculin", sig: "tone" },
  { mot: "tonneau", genre: "masculin", sig: "barrel" },
  { mot: "tonnerre", genre: "masculin", sig: "thunder" },
  { mot: "torsion", genre: "féminin", sig: "twist" },
  { mot: "tortue", genre: "féminin", sig: "turtle" },
  { mot: "torture", genre: "féminin", sig: "torture" },
  { mot: "total", genre: "masculin", sig: "total" },
  { mot: "tour", genre: "masculin", sig: "turn; round; tour; lap" },
  { mot: "tour", genre: "féminin", sig: "tower" },
  { mot: "tournoi", genre: "masculin", sig: "tournament" },
  { mot: "trace", genre: "féminin", sig: "trace" },
  { mot: "traction", genre: "féminin", sig: "pull" },
  { mot: "tradition", genre: "féminin", sig: "tradition" },
  { mot: "tragédie", genre: "féminin", sig: "tragedy" },
  { mot: "train", genre: "masculin", sig: "train" },
  { mot: "traitement", genre: "masculin", sig: "treatment" },
  { mot: "trajet", genre: "masculin", sig: "ride" },
  { mot: "tranche", genre: "féminin", sig: "slice" },
  { mot: "tranquillité", genre: "féminin", sig: "quiet" },
  { mot: "transfert", genre: "masculin", sig: "transfer" },
  { mot: "transport", genre: "masculin", sig: "transport" },
  { mot: "trauma", genre: "masculin", sig: "trauma" },
  { mot: "travail", genre: "masculin", sig: "work; labor" },
  { mot: "travaux", genre: "masculin", sig: "(road, construction) works" },
  { mot: "tremblement", genre: "masculin", sig: "tremor; trembling" },
  { mot: "tremblement de terre", genre: "masculin", sig: "earthquake" },
  { mot: "trésor", genre: "masculin", sig: "treasure" },
  { mot: "tribu", genre: "féminin", sig: "tribe" },
  { mot: "tribunal", genre: "masculin", sig: "court; tribunal" },
  { mot: "tronc", genre: "masculin", sig: "trunk" },
  { mot: "trône", genre: "masculin", sig: "throne" },
  { mot: "trou", genre: "masculin", sig: "hole" },
  { mot: "truc", genre: "masculin", sig: "thing" },
  { mot: "tube", genre: "masculin", sig: "tube" },
  { mot: "tunnel", genre: "masculin", sig: "tunnel" },
  { mot: "tuyau", genre: "masculin", sig: "pipe" },
  { mot: "type", genre: "masculin", sig: "dude; type" },
  { mot: "uniforme", genre: "masculin", sig: "uniform" },
  { mot: "unité", genre: "féminin", sig: "unit" },
  { mot: "univers", genre: "masculin", sig: "universe" },
  { mot: "urgence", genre: "féminin", sig: "emergency" },
  { mot: "usine", genre: "féminin", sig: "factory" },
  { mot: "vacances", genre: "féminin", sig: "vacation; holiday" },
  { mot: "vache", genre: "féminin", sig: "cow" },
  { mot: "vagin", genre: "masculin", sig: "vagina" },
  { mot: "vague", genre: "féminin", sig: "wave" },
  { mot: "vaisseau", genre: "masculin", sig: "vessel" },
  { mot: "valeur", genre: "féminin", sig: "worth; value" },
  { mot: "valise", genre: "féminin", sig: "suitcase" },
  { mot: "vampire", genre: "masculin", sig: "vampire" },
  { mot: "vapeur", genre: "féminin", sig: "steam" },
  { mot: "véhicule", genre: "masculin", sig: "vehicle" },
  { mot: "vélo", genre: "masculin", sig: "bike" },
  { mot: "vengeance", genre: "féminin", sig: "revenge" },
  { mot: "vent", genre: "masculin", sig: "wind" },
  { mot: "vente", genre: "féminin", sig: "sale" },
  { mot: "ventilateur", genre: "masculin", sig: "fan" },
  { mot: "ventre", genre: "masculin", sig: "stomach" },
  { mot: "vérification", genre: "féminin", sig: "verification; check; examination (of quality, etc.)" },
  { mot: "vérité", genre: "féminin", sig: "truth" },
  { mot: "vernis", genre: "masculin", sig: "polish" },
  { mot: "verre", genre: "masculin", sig: "glass" },
  { mot: "verrou", genre: "masculin", sig: "lock" },
  { mot: "version", genre: "féminin", sig: "version" },
  { mot: "vert", genre: "masculin", sig: "green" },
  { mot: "veste", genre: "féminin", sig: "jacket" },
  { mot: "vêtements", genre: "masculin", sig: "clothes" },
  { mot: "viande", genre: "féminin", sig: "meat" },
  { mot: "victime", genre: "féminin", sig: "victim" },
  { mot: "victoire", genre: "féminin", sig: "victory; win" },
  { mot: "vidéo", genre: "féminin", sig: "video" },
  { mot: "vie", genre: "féminin", sig: "life; lifetime" },
  { mot: "villa", genre: "féminin", sig: "villa" },
  { mot: "village", genre: "masculin", sig: "village" },
  { mot: "ville", genre: "féminin", sig: "city; town; village" },
  { mot: "vin", genre: "masculin", sig: "wine" },
  { mot: "violence", genre: "féminin", sig: "violence" },
  { mot: "virus", genre: "masculin", sig: "virus" },
  { mot: "vis", genre: "féminin", sig: "screw" },
  { mot: "visage", genre: "masculin", sig: "face" },
  { mot: "visée", genre: "féminin", sig: "aim" },
  { mot: "vision", genre: "féminin", sig: "vision" },
  { mot: "visite", genre: "féminin", sig: "visit" },
  { mot: "vitesse", genre: "féminin", sig: "speed" },
  { mot: "vodka", genre: "féminin", sig: "vodka" },
  { mot: "voie", genre: "féminin", sig: "lane" },
  { mot: "voile", genre: "féminin", sig: "sail" },
  { mot: "voiture", genre: "féminin", sig: "car" },
  { mot: "voix", genre: "féminin", sig: "voice" },
  { mot: "vol", genre: "masculin", sig: "flight" },
  { mot: "vol", genre: "masculin", sig: "robbery; theft" },
  { mot: "vote", genre: "masculin", sig: "vote" },
  { mot: "voûte", genre: "féminin", sig: "vault" },
  { mot: "voyage", genre: "masculin", sig: "journey; travel; trip" },
  { mot: "vue", genre: "féminin", sig: "sight; view" },
  { mot: "week-end", genre: "masculin", sig: "weekend" },
  { mot: "weekend", genre: "masculin", sig: "weekend" },
  { mot: "whisky", genre: "masculin", sig: "whiskey" },
  { mot: "zombie", genre: "masculin", sig: "zombie" },
  { mot: "zone", genre: "féminin", sig: "zone" },
  { mot: "zoo", genre: "masculin", sig: "zoo" }
];