const géographie = [
  { mot: "afrique", genre: "féminin", sig: "africa" },
  { mot: "allemagne", genre: "féminin", sig: "germany" },
  { mot: "amerique du nord", genre: "féminin", sig: "north america" },
  { mot: "amerique du sud", genre: "féminin", sig: "south america" },
  { mot: "angleterre", genre: "féminin", sig: "england" },
  { mot: "antartique", genre: "féminin", sig: "antarctica" },
  { mot: "asie", genre: "féminin", sig: "asia" },
  { mot: "autriche", genre: "féminin", sig: "austria" },
  { mot: "belgique", genre: "féminin", sig: "belgium" },
  { mot: "canada", genre: "masculin", sig: "canada" },
  { mot: "chine", genre: "féminin", sig: "china" },
  { mot: "corée", genre: "masculin", sig: "korea" },
  { mot: "écosse", genre: "féminin", sig: "scotland" },
  { mot: "espagne", genre: "féminin", sig: "spain" },
  { mot: "europe", genre: "féminin", sig: "europe" },
  { mot: "finlande", genre: "féminin", sig: "finland" },
  { mot: "france", genre: "féminin", sig: "france" },
  { mot: "grèce", genre: "féminin", sig: "greece" },
  { mot: "guatemala", genre: "masculin", sig: "guatemala" },
  { mot: "inde", genre: "féminin", sig: "india" },
  { mot: "indonésie", genre: "féminin", sig: "indonesia" },
  { mot: "irlande", genre: "féminin", sig: "ireland" },
  { mot: "italie", genre: "féminin", sig: "italy" },
  { mot: "japon", genre: "masculin", sig: "japan" },
  { mot: "maroc", genre: "masculin", sig: "morocco" },
  { mot: "mexique", genre: "masculin", sig: "mexico" },
  { mot: "océanie", genre: "féminin", sig: "oceania" },
  { mot: "portugal", genre: "masculin", sig: "portugal" },
  { mot: "suède", genre: "féminin", sig: "sweden" },
  { mot: "suisse", genre: "féminin", sig: "switzerland" },
  { mot: "thaïlande", genre: "féminin", sig: "thailand" },
  { mot: "tunisie", genre: "féminin", sig: "tunisia" },
  { mot: "ukraine", genre: "féminin", sig: "ukraine" }
];